// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit.sql

package dbgen

import (
	"context"
	"time"
)

const appendAuditCheckpoint = `-- name: AppendAuditCheckpoint :one
INSERT INTO audit_checkpoints (
    partition,
    first_sequence,
    last_sequence,
    first_hash,
    last_hash,
    record_count,
    created_at_utc,
    signing_key_id,
    signature,
    schema_version
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING partition, first_sequence, last_sequence, first_hash, last_hash, record_count, created_at_utc, signing_key_id, signature, schema_version
`

type AppendAuditCheckpointParams struct {
	Partition     string    `json:"partition"`
	FirstSequence int64     `json:"first_sequence"`
	LastSequence  int64     `json:"last_sequence"`
	FirstHash     []byte    `json:"first_hash"`
	LastHash      []byte    `json:"last_hash"`
	RecordCount   int32     `json:"record_count"`
	CreatedAtUtc  time.Time `json:"created_at_utc"`
	SigningKeyID  string    `json:"signing_key_id"`
	Signature     []byte    `json:"signature"`
	SchemaVersion int32     `json:"schema_version"`
}

func (q *Queries) AppendAuditCheckpoint(ctx context.Context, arg AppendAuditCheckpointParams) (AuditCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, appendAuditCheckpoint,
		arg.Partition,
		arg.FirstSequence,
		arg.LastSequence,
		arg.FirstHash,
		arg.LastHash,
		arg.RecordCount,
		arg.CreatedAtUtc,
		arg.SigningKeyID,
		arg.Signature,
		arg.SchemaVersion,
	)
	var i AuditCheckpoint
	err := row.Scan(
		&i.Partition,
		&i.FirstSequence,
		&i.LastSequence,
		&i.FirstHash,
		&i.LastHash,
		&i.RecordCount,
		&i.CreatedAtUtc,
		&i.SigningKeyID,
		&i.Signature,
		&i.SchemaVersion,
	)
	return i, err
}

const appendAuditRecord = `-- name: AppendAuditRecord :one
INSERT INTO audit_records (
    audit_id,
    partition,
    sequence,
    actor_id,
    actor_type,
    action,
    target_type,
    target_id,
    environment,
    market_scope,
    occurred_at_utc,
    recorded_at_utc,
    reason,
    correlation_id,
    causation_id,
    policy_version,
    result,
    before_digest,
    after_digest,
    previous_hash,
    record_hash,
    signing_key_id,
    schema_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20, $21, $22, $23
)
RETURNING audit_id, partition, sequence, actor_id, actor_type, action, target_type, target_id, environment, market_scope, occurred_at_utc, recorded_at_utc, reason, correlation_id, causation_id, policy_version, result, before_digest, after_digest, previous_hash, record_hash, signing_key_id, schema_version
`

type AppendAuditRecordParams struct {
	AuditID       string    `json:"audit_id"`
	Partition     string    `json:"partition"`
	Sequence      int64     `json:"sequence"`
	ActorID       string    `json:"actor_id"`
	ActorType     string    `json:"actor_type"`
	Action        string    `json:"action"`
	TargetType    string    `json:"target_type"`
	TargetID      string    `json:"target_id"`
	Environment   string    `json:"environment"`
	MarketScope   string    `json:"market_scope"`
	OccurredAtUtc time.Time `json:"occurred_at_utc"`
	RecordedAtUtc time.Time `json:"recorded_at_utc"`
	Reason        string    `json:"reason"`
	CorrelationID string    `json:"correlation_id"`
	CausationID   string    `json:"causation_id"`
	PolicyVersion string    `json:"policy_version"`
	Result        string    `json:"result"`
	BeforeDigest  string    `json:"before_digest"`
	AfterDigest   string    `json:"after_digest"`
	PreviousHash  []byte    `json:"previous_hash"`
	RecordHash    []byte    `json:"record_hash"`
	SigningKeyID  string    `json:"signing_key_id"`
	SchemaVersion int32     `json:"schema_version"`
}

// The append-only evidence write.
//
// There is no ON CONFLICT clause here, deliberately. A duplicate audit_id is a genuine
// conflict between two different facts, and silently returning the existing row would make
// the second write disappear while the caller believed it was recorded. The ledger is
// idempotent because a repeat is a retry; an audit record is idempotent because a repeat is
// a contradiction, and those are different situations that happen to look alike.
func (q *Queries) AppendAuditRecord(ctx context.Context, arg AppendAuditRecordParams) (AuditRecord, error) {
	row := q.db.QueryRowContext(ctx, appendAuditRecord,
		arg.AuditID,
		arg.Partition,
		arg.Sequence,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Environment,
		arg.MarketScope,
		arg.OccurredAtUtc,
		arg.RecordedAtUtc,
		arg.Reason,
		arg.CorrelationID,
		arg.CausationID,
		arg.PolicyVersion,
		arg.Result,
		arg.BeforeDigest,
		arg.AfterDigest,
		arg.PreviousHash,
		arg.RecordHash,
		arg.SigningKeyID,
		arg.SchemaVersion,
	)
	var i AuditRecord
	err := row.Scan(
		&i.AuditID,
		&i.Partition,
		&i.Sequence,
		&i.ActorID,
		&i.ActorType,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Environment,
		&i.MarketScope,
		&i.OccurredAtUtc,
		&i.RecordedAtUtc,
		&i.Reason,
		&i.CorrelationID,
		&i.CausationID,
		&i.PolicyVersion,
		&i.Result,
		&i.BeforeDigest,
		&i.AfterDigest,
		&i.PreviousHash,
		&i.RecordHash,
		&i.SigningKeyID,
		&i.SchemaVersion,
	)
	return i, err
}

const getAuditRecord = `-- name: GetAuditRecord :one
SELECT audit_id, partition, sequence, actor_id, actor_type, action, target_type, target_id, environment, market_scope, occurred_at_utc, recorded_at_utc, reason, correlation_id, causation_id, policy_version, result, before_digest, after_digest, previous_hash, record_hash, signing_key_id, schema_version FROM audit_records WHERE audit_id = $1
`

func (q *Queries) GetAuditRecord(ctx context.Context, auditID string) (AuditRecord, error) {
	row := q.db.QueryRowContext(ctx, getAuditRecord, auditID)
	var i AuditRecord
	err := row.Scan(
		&i.AuditID,
		&i.Partition,
		&i.Sequence,
		&i.ActorID,
		&i.ActorType,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Environment,
		&i.MarketScope,
		&i.OccurredAtUtc,
		&i.RecordedAtUtc,
		&i.Reason,
		&i.CorrelationID,
		&i.CausationID,
		&i.PolicyVersion,
		&i.Result,
		&i.BeforeDigest,
		&i.AfterDigest,
		&i.PreviousHash,
		&i.RecordHash,
		&i.SigningKeyID,
		&i.SchemaVersion,
	)
	return i, err
}

const getLastAuditRecordInPartition = `-- name: GetLastAuditRecordInPartition :one
SELECT audit_id, partition, sequence, actor_id, actor_type, action, target_type, target_id, environment, market_scope, occurred_at_utc, recorded_at_utc, reason, correlation_id, causation_id, policy_version, result, before_digest, after_digest, previous_hash, record_hash, signing_key_id, schema_version FROM audit_records
WHERE partition = $1
ORDER BY sequence DESC
LIMIT 1
`

func (q *Queries) GetLastAuditRecordInPartition(ctx context.Context, partition string) (AuditRecord, error) {
	row := q.db.QueryRowContext(ctx, getLastAuditRecordInPartition, partition)
	var i AuditRecord
	err := row.Scan(
		&i.AuditID,
		&i.Partition,
		&i.Sequence,
		&i.ActorID,
		&i.ActorType,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Environment,
		&i.MarketScope,
		&i.OccurredAtUtc,
		&i.RecordedAtUtc,
		&i.Reason,
		&i.CorrelationID,
		&i.CausationID,
		&i.PolicyVersion,
		&i.Result,
		&i.BeforeDigest,
		&i.AfterDigest,
		&i.PreviousHash,
		&i.RecordHash,
		&i.SigningKeyID,
		&i.SchemaVersion,
	)
	return i, err
}

const getLatestAuditCheckpoint = `-- name: GetLatestAuditCheckpoint :one
SELECT partition, first_sequence, last_sequence, first_hash, last_hash, record_count, created_at_utc, signing_key_id, signature, schema_version FROM audit_checkpoints
WHERE partition = $1
ORDER BY last_sequence DESC
LIMIT 1
`

func (q *Queries) GetLatestAuditCheckpoint(ctx context.Context, partition string) (AuditCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getLatestAuditCheckpoint, partition)
	var i AuditCheckpoint
	err := row.Scan(
		&i.Partition,
		&i.FirstSequence,
		&i.LastSequence,
		&i.FirstHash,
		&i.LastHash,
		&i.RecordCount,
		&i.CreatedAtUtc,
		&i.SigningKeyID,
		&i.Signature,
		&i.SchemaVersion,
	)
	return i, err
}

const getNextAuditSequence = `-- name: GetNextAuditSequence :one
SELECT coalesce(max(r.sequence), 0)::bigint + 1 AS next_sequence
FROM audit_records r
WHERE r.partition = $1
`

// The next sequence number for a partition.
//
// Computed as max + 1 rather than read from a counter table so that the number is always
// derived from the chain that actually exists. A counter table can disagree with the records
// after a restore, and a gap detected only at verification time is a gap that has already
// been written to.
func (q *Queries) GetNextAuditSequence(ctx context.Context, partition string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNextAuditSequence, partition)
	var next_sequence int32
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const insertAuditDeletionEvent = `-- name: InsertAuditDeletionEvent :one
INSERT INTO audit_deletion_events (
    audit_id,
    partition,
    first_sequence,
    last_sequence,
    requested_by,
    approved_by,
    deleted_at_utc
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING audit_id, partition, first_sequence, last_sequence, requested_by, approved_by, deleted_at_utc
`

type InsertAuditDeletionEventParams struct {
	AuditID       string    `json:"audit_id"`
	Partition     string    `json:"partition"`
	FirstSequence int64     `json:"first_sequence"`
	LastSequence  int64     `json:"last_sequence"`
	RequestedBy   string    `json:"requested_by"`
	ApprovedBy    string    `json:"approved_by"`
	DeletedAtUtc  time.Time `json:"deleted_at_utc"`
}

func (q *Queries) InsertAuditDeletionEvent(ctx context.Context, arg InsertAuditDeletionEventParams) (AuditDeletionEvent, error) {
	row := q.db.QueryRowContext(ctx, insertAuditDeletionEvent,
		arg.AuditID,
		arg.Partition,
		arg.FirstSequence,
		arg.LastSequence,
		arg.RequestedBy,
		arg.ApprovedBy,
		arg.DeletedAtUtc,
	)
	var i AuditDeletionEvent
	err := row.Scan(
		&i.AuditID,
		&i.Partition,
		&i.FirstSequence,
		&i.LastSequence,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.DeletedAtUtc,
	)
	return i, err
}

const listAuditDeletionEvents = `-- name: ListAuditDeletionEvents :many
SELECT audit_id, partition, first_sequence, last_sequence, requested_by, approved_by, deleted_at_utc FROM audit_deletion_events
ORDER BY deleted_at_utc DESC
LIMIT $1
`

// The retained record of a deletion. Deleting evidence is permitted under a two-person
// approval after expiry, and the fact that it happened is itself kept, so this table is
// append-only in the same way the evidence it describes is.
func (q *Queries) ListAuditDeletionEvents(ctx context.Context, limit int32) ([]AuditDeletionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditDeletionEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditDeletionEvent{}
	for rows.Next() {
		var i AuditDeletionEvent
		if err := rows.Scan(
			&i.AuditID,
			&i.Partition,
			&i.FirstSequence,
			&i.LastSequence,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.DeletedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditRecordsByCorrelation = `-- name: ListAuditRecordsByCorrelation :many
SELECT audit_id, partition, sequence, actor_id, actor_type, action, target_type, target_id, environment, market_scope, occurred_at_utc, recorded_at_utc, reason, correlation_id, causation_id, policy_version, result, before_digest, after_digest, previous_hash, record_hash, signing_key_id, schema_version FROM audit_records
WHERE correlation_id = $1 AND correlation_id <> ''
ORDER BY recorded_at_utc, partition, sequence
`

func (q *Queries) ListAuditRecordsByCorrelation(ctx context.Context, correlationID string) ([]AuditRecord, error) {
	rows, err := q.db.QueryContext(ctx, listAuditRecordsByCorrelation, correlationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditRecord{}
	for rows.Next() {
		var i AuditRecord
		if err := rows.Scan(
			&i.AuditID,
			&i.Partition,
			&i.Sequence,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Environment,
			&i.MarketScope,
			&i.OccurredAtUtc,
			&i.RecordedAtUtc,
			&i.Reason,
			&i.CorrelationID,
			&i.CausationID,
			&i.PolicyVersion,
			&i.Result,
			&i.BeforeDigest,
			&i.AfterDigest,
			&i.PreviousHash,
			&i.RecordHash,
			&i.SigningKeyID,
			&i.SchemaVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditRecordsForActor = `-- name: ListAuditRecordsForActor :many
SELECT audit_id, partition, sequence, actor_id, actor_type, action, target_type, target_id, environment, market_scope, occurred_at_utc, recorded_at_utc, reason, correlation_id, causation_id, policy_version, result, before_digest, after_digest, previous_hash, record_hash, signing_key_id, schema_version FROM audit_records
WHERE actor_id = $1
ORDER BY recorded_at_utc DESC
LIMIT $2
`

type ListAuditRecordsForActorParams struct {
	ActorID string `json:"actor_id"`
	Limit   int32  `json:"limit"`
}

// Bounded on purpose. An unbounded actor history is a table scan over the evidence that has
// to survive for seven years, and the callers that need it are investigations rather than
// request handlers.
func (q *Queries) ListAuditRecordsForActor(ctx context.Context, arg ListAuditRecordsForActorParams) ([]AuditRecord, error) {
	rows, err := q.db.QueryContext(ctx, listAuditRecordsForActor, arg.ActorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditRecord{}
	for rows.Next() {
		var i AuditRecord
		if err := rows.Scan(
			&i.AuditID,
			&i.Partition,
			&i.Sequence,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Environment,
			&i.MarketScope,
			&i.OccurredAtUtc,
			&i.RecordedAtUtc,
			&i.Reason,
			&i.CorrelationID,
			&i.CausationID,
			&i.PolicyVersion,
			&i.Result,
			&i.BeforeDigest,
			&i.AfterDigest,
			&i.PreviousHash,
			&i.RecordHash,
			&i.SigningKeyID,
			&i.SchemaVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditRecordsInPartitionRange = `-- name: ListAuditRecordsInPartitionRange :many
SELECT audit_id, partition, sequence, actor_id, actor_type, action, target_type, target_id, environment, market_scope, occurred_at_utc, recorded_at_utc, reason, correlation_id, causation_id, policy_version, result, before_digest, after_digest, previous_hash, record_hash, signing_key_id, schema_version FROM audit_records
WHERE partition = $1
  AND sequence >= $2
  AND sequence <= $3
ORDER BY sequence
`

type ListAuditRecordsInPartitionRangeParams struct {
	Partition  string `json:"partition"`
	Sequence   int64  `json:"sequence"`
	Sequence_2 int64  `json:"sequence_2"`
}

func (q *Queries) ListAuditRecordsInPartitionRange(ctx context.Context, arg ListAuditRecordsInPartitionRangeParams) ([]AuditRecord, error) {
	rows, err := q.db.QueryContext(ctx, listAuditRecordsInPartitionRange, arg.Partition, arg.Sequence, arg.Sequence_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditRecord{}
	for rows.Next() {
		var i AuditRecord
		if err := rows.Scan(
			&i.AuditID,
			&i.Partition,
			&i.Sequence,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Environment,
			&i.MarketScope,
			&i.OccurredAtUtc,
			&i.RecordedAtUtc,
			&i.Reason,
			&i.CorrelationID,
			&i.CausationID,
			&i.PolicyVersion,
			&i.Result,
			&i.BeforeDigest,
			&i.AfterDigest,
			&i.PreviousHash,
			&i.RecordHash,
			&i.SigningKeyID,
			&i.SchemaVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
