// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ledger.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const appendEntry = `-- name: AppendEntry :one
INSERT INTO ledger.entry (
    entry_id,
    source_command_id,
    correlation_id,
    corrects_entry_id,
    reason,
    posted_at,
    idempotency_key,
    content_hash
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (source_command_id, idempotency_key) DO UPDATE
    SET idempotency_key = ledger.entry.idempotency_key
RETURNING entry_id, sequence_no, source_command_id, correlation_id, corrects_entry_id, reason, posted_at, idempotency_key, content_hash
`

type AppendEntryParams struct {
	EntryID         string         `json:"entry_id"`
	SourceCommandID string         `json:"source_command_id"`
	CorrelationID   string         `json:"correlation_id"`
	CorrectsEntryID sql.NullString `json:"corrects_entry_id"`
	Reason          sql.NullString `json:"reason"`
	PostedAt        time.Time      `json:"posted_at"`
	IdempotencyKey  string         `json:"idempotency_key"`
	ContentHash     []byte         `json:"content_hash"`
}

// The entry header for one posting set.
//
// Idempotent rather than erroring on a repeat, because a retried command must not create a
// second financial fact.
//
// The conflict target is the PAIR (source_command_id, idempotency_key), because that is what
// the unique index covers: entry_idempotency_uniq is on the pair, not on the key alone, since
// the same key issued under a different command is a different posting and collapsing them
// would lose a financial fact. Writing ON CONFLICT (idempotency_key) looks equivalent and is
// not -- it has no matching unique index, so the statement fails at runtime with "there is no
// unique or exclusion constraint matching the ON CONFLICT specification". Neither sqlc nor
// sqlc vet catches that, which is why scripts/rehearse_migrations.py executes every query
// against the real schema.
func (q *Queries) AppendEntry(ctx context.Context, arg AppendEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRowContext(ctx, appendEntry,
		arg.EntryID,
		arg.SourceCommandID,
		arg.CorrelationID,
		arg.CorrectsEntryID,
		arg.Reason,
		arg.PostedAt,
		arg.IdempotencyKey,
		arg.ContentHash,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.EntryID,
		&i.SequenceNo,
		&i.SourceCommandID,
		&i.CorrelationID,
		&i.CorrectsEntryID,
		&i.Reason,
		&i.PostedAt,
		&i.IdempotencyKey,
		&i.ContentHash,
	)
	return i, err
}

const checkEntryBalances = `-- name: CheckEntryBalances :one
SELECT
    l.entry_id,
    l.asset,
    sum(CASE WHEN l.direction = 'DEBIT' THEN l.amount ELSE -l.amount END) AS net_amount,
    count(*)::bigint AS leg_count
FROM ledger.line l
WHERE l.entry_id = $1
GROUP BY l.entry_id, l.asset
ORDER BY l.asset
`

type CheckEntryBalancesRow struct {
	EntryID   string `json:"entry_id"`
	Asset     string `json:"asset"`
	NetAmount int64  `json:"net_amount"`
	LegCount  int64  `json:"leg_count"`
}

// The per-asset balance check, computed rather than read.
//
// This is the query the reconciliation path uses to decide whether a posting set is a valid
// correction or a defect. The constraint makes the database refuse an unbalanced entry; this
// makes the application able to explain one without reproducing the trigger's logic.
func (q *Queries) CheckEntryBalances(ctx context.Context, entryID string) (CheckEntryBalancesRow, error) {
	row := q.db.QueryRowContext(ctx, checkEntryBalances, entryID)
	var i CheckEntryBalancesRow
	err := row.Scan(
		&i.EntryID,
		&i.Asset,
		&i.NetAmount,
		&i.LegCount,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT entry_id, sequence_no, source_command_id, correlation_id, corrects_entry_id, reason, posted_at, idempotency_key, content_hash FROM ledger.entry WHERE entry_id = $1
`

func (q *Queries) GetEntry(ctx context.Context, entryID string) (LedgerEntry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, entryID)
	var i LedgerEntry
	err := row.Scan(
		&i.EntryID,
		&i.SequenceNo,
		&i.SourceCommandID,
		&i.CorrelationID,
		&i.CorrectsEntryID,
		&i.Reason,
		&i.PostedAt,
		&i.IdempotencyKey,
		&i.ContentHash,
	)
	return i, err
}

const getEntryByIdempotencyKey = `-- name: GetEntryByIdempotencyKey :one
SELECT entry_id, sequence_no, source_command_id, correlation_id, corrects_entry_id, reason, posted_at, idempotency_key, content_hash FROM ledger.entry
WHERE source_command_id = $1 AND idempotency_key = $2
`

type GetEntryByIdempotencyKeyParams struct {
	SourceCommandID string `json:"source_command_id"`
	IdempotencyKey  string `json:"idempotency_key"`
}

// Takes both halves of the pair for the same reason AppendEntry does. Looking up by the key
// alone would return an arbitrary posting among every command that reused the key, which is
// exactly the ambiguity the unique index exists to prevent.
func (q *Queries) GetEntryByIdempotencyKey(ctx context.Context, arg GetEntryByIdempotencyKeyParams) (LedgerEntry, error) {
	row := q.db.QueryRowContext(ctx, getEntryByIdempotencyKey, arg.SourceCommandID, arg.IdempotencyKey)
	var i LedgerEntry
	err := row.Scan(
		&i.EntryID,
		&i.SequenceNo,
		&i.SourceCommandID,
		&i.CorrelationID,
		&i.CorrectsEntryID,
		&i.Reason,
		&i.PostedAt,
		&i.IdempotencyKey,
		&i.ContentHash,
	)
	return i, err
}

const insertLine = `-- name: InsertLine :exec
INSERT INTO ledger.line (entry_id, line_no, account, subject, asset, direction, amount)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertLineParams struct {
	EntryID   string `json:"entry_id"`
	LineNo    int32  `json:"line_no"`
	Account   string `json:"account"`
	Subject   string `json:"subject"`
	Asset     string `json:"asset"`
	Direction string `json:"direction"`
	Amount    string `json:"amount"`
}

// The caller inserts the header and then its legs. There is no single statement that writes
// both, because the balance trigger is deferred to the end of the transaction: a set that
// does not balance is refused at COMMIT rather than half-written. That deferral is the point,
// so the legs are written by a separate statement rather than a CTE.
func (q *Queries) InsertLine(ctx context.Context, arg InsertLineParams) error {
	_, err := q.db.ExecContext(ctx, insertLine,
		arg.EntryID,
		arg.LineNo,
		arg.Account,
		arg.Subject,
		arg.Asset,
		arg.Direction,
		arg.Amount,
	)
	return err
}

const listCorrectionsForEntry = `-- name: ListCorrectionsForEntry :many
SELECT entry_id, sequence_no, source_command_id, correlation_id, corrects_entry_id, reason, posted_at, idempotency_key, content_hash FROM ledger.entry
WHERE corrects_entry_id = $1
ORDER BY sequence_no
`

func (q *Queries) ListCorrectionsForEntry(ctx context.Context, correctsEntryID sql.NullString) ([]LedgerEntry, error) {
	rows, err := q.db.QueryContext(ctx, listCorrectionsForEntry, correctsEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.EntryID,
			&i.SequenceNo,
			&i.SourceCommandID,
			&i.CorrelationID,
			&i.CorrectsEntryID,
			&i.Reason,
			&i.PostedAt,
			&i.IdempotencyKey,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByCorrelation = `-- name: ListEntriesByCorrelation :many
SELECT entry_id, sequence_no, source_command_id, correlation_id, corrects_entry_id, reason, posted_at, idempotency_key, content_hash FROM ledger.entry
WHERE correlation_id = $1
ORDER BY sequence_no
`

func (q *Queries) ListEntriesByCorrelation(ctx context.Context, correlationID string) ([]LedgerEntry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByCorrelation, correlationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.EntryID,
			&i.SequenceNo,
			&i.SourceCommandID,
			&i.CorrelationID,
			&i.CorrectsEntryID,
			&i.Reason,
			&i.PostedAt,
			&i.IdempotencyKey,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinesForEntry = `-- name: ListLinesForEntry :many
SELECT entry_id, line_no, account, subject, asset, direction, amount FROM ledger.line WHERE entry_id = $1 ORDER BY line_no
`

func (q *Queries) ListLinesForEntry(ctx context.Context, entryID string) ([]LedgerLine, error) {
	rows, err := q.db.QueryContext(ctx, listLinesForEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerLine{}
	for rows.Next() {
		var i LedgerLine
		if err := rows.Scan(
			&i.EntryID,
			&i.LineNo,
			&i.Account,
			&i.Subject,
			&i.Asset,
			&i.Direction,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
