// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: model_registry.sql

package dbgen

import (
	"context"
	"time"
)

const getModel = `-- name: GetModel :one
SELECT model_id, version, owner, author, training_dataset_fingerprint, code_revision, feature_specification, evaluation_results, limitations, approval_record, deployment_scope, monitoring_policy, rollback_artifact, state, registered_at_utc, last_audit_id, updated_by, updated_at_utc FROM model_registry WHERE model_id = $1
`

func (q *Queries) GetModel(ctx context.Context, modelID string) (ModelRegistry, error) {
	row := q.db.QueryRowContext(ctx, getModel, modelID)
	var i ModelRegistry
	err := row.Scan(
		&i.ModelID,
		&i.Version,
		&i.Owner,
		&i.Author,
		&i.TrainingDatasetFingerprint,
		&i.CodeRevision,
		&i.FeatureSpecification,
		&i.EvaluationResults,
		&i.Limitations,
		&i.ApprovalRecord,
		&i.DeploymentScope,
		&i.MonitoringPolicy,
		&i.RollbackArtifact,
		&i.State,
		&i.RegisteredAtUtc,
		&i.LastAuditID,
		&i.UpdatedBy,
		&i.UpdatedAtUtc,
	)
	return i, err
}

const getRevocation = `-- name: GetRevocation :one
SELECT identity, model_id, model_version, revoked_at_utc, reason, evidence_ref, revoked_by FROM workload_revocations WHERE identity = $1
`

func (q *Queries) GetRevocation(ctx context.Context, identity string) (WorkloadRevocation, error) {
	row := q.db.QueryRowContext(ctx, getRevocation, identity)
	var i WorkloadRevocation
	err := row.Scan(
		&i.Identity,
		&i.ModelID,
		&i.ModelVersion,
		&i.RevokedAtUtc,
		&i.Reason,
		&i.EvidenceRef,
		&i.RevokedBy,
	)
	return i, err
}

const getTransitionIdempotency = `-- name: GetTransitionIdempotency :one
SELECT idempotency_scope, idempotency_key, request_fingerprint, model_id, from_state, to_state, audit_id, applied_at_utc FROM model_transition_idempotency
WHERE idempotency_scope = $1 AND idempotency_key = $2
`

type GetTransitionIdempotencyParams struct {
	IdempotencyScope string `json:"idempotency_scope"`
	IdempotencyKey   string `json:"idempotency_key"`
}

// The transition previously applied under this scope and key, if any.
//
// The journal calls this before deciding to apply, and its absence is what tells the journal
// this is a first attempt rather than a retry.
func (q *Queries) GetTransitionIdempotency(ctx context.Context, arg GetTransitionIdempotencyParams) (ModelTransitionIdempotency, error) {
	row := q.db.QueryRowContext(ctx, getTransitionIdempotency, arg.IdempotencyScope, arg.IdempotencyKey)
	var i ModelTransitionIdempotency
	err := row.Scan(
		&i.IdempotencyScope,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.ModelID,
		&i.FromState,
		&i.ToState,
		&i.AuditID,
		&i.AppliedAtUtc,
	)
	return i, err
}

const getWorkloadIdentity = `-- name: GetWorkloadIdentity :one
SELECT identity, model_id, model_version, scope, issued_at_utc, expires_at_utc FROM workload_identities WHERE identity = $1
`

func (q *Queries) GetWorkloadIdentity(ctx context.Context, identity string) (WorkloadIdentity, error) {
	row := q.db.QueryRowContext(ctx, getWorkloadIdentity, identity)
	var i WorkloadIdentity
	err := row.Scan(
		&i.Identity,
		&i.ModelID,
		&i.ModelVersion,
		&i.Scope,
		&i.IssuedAtUtc,
		&i.ExpiresAtUtc,
	)
	return i, err
}

const insertModel = `-- name: InsertModel :one

INSERT INTO model_registry (
    model_id,
    version,
    owner,
    author,
    training_dataset_fingerprint,
    code_revision,
    feature_specification,
    evaluation_results,
    limitations,
    approval_record,
    deployment_scope,
    monitoring_policy,
    rollback_artifact,
    state,
    registered_at_utc,
    last_audit_id,
    updated_by,
    updated_at_utc
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
RETURNING model_id, version, owner, author, training_dataset_fingerprint, code_revision, feature_specification, evaluation_results, limitations, approval_record, deployment_scope, monitoring_policy, rollback_artifact, state, registered_at_utc, last_audit_id, updated_by, updated_at_utc
`

type InsertModelParams struct {
	ModelID                    string    `json:"model_id"`
	Version                    string    `json:"version"`
	Owner                      string    `json:"owner"`
	Author                     string    `json:"author"`
	TrainingDatasetFingerprint string    `json:"training_dataset_fingerprint"`
	CodeRevision               string    `json:"code_revision"`
	FeatureSpecification       string    `json:"feature_specification"`
	EvaluationResults          string    `json:"evaluation_results"`
	Limitations                string    `json:"limitations"`
	ApprovalRecord             string    `json:"approval_record"`
	DeploymentScope            string    `json:"deployment_scope"`
	MonitoringPolicy           string    `json:"monitoring_policy"`
	RollbackArtifact           string    `json:"rollback_artifact"`
	State                      string    `json:"state"`
	RegisteredAtUtc            time.Time `json:"registered_at_utc"`
	LastAuditID                string    `json:"last_audit_id"`
	UpdatedBy                  string    `json:"updated_by"`
	UpdatedAtUtc               time.Time `json:"updated_at_utc"`
}

// Queries against the model registry, the workload identities that may serve it, the
// revocations that stop them, and the idempotency ledger.
//
// Authority, and why these queries are shaped the way they are.
//
// The Go package in services/control-plane/model decides; these queries only persist what it
// decided. Nothing here is allowed to become a second decision path, and the shapes below are
// chosen to make that structurally difficult rather than merely documented:
//
//   - There is no UPDATE that can move a model between arbitrary states. The only state query
//     writes the target state alongside the audit record that caused it, so a caller cannot
//     produce a state whose origin is not in the audit chain.
//   - There is no DELETE anywhere in this file. The three tables that must not lose a row
//     (revocations, the idempotency ledger, and the registry itself) are protected by triggers
//     in the migration; a query that asked to delete one would fail at runtime, and its absence
//     here means nobody writes code expecting it to work.
//   - The revocation queries answer containment questions by reading recorded revocations
//     rather than by reading live identities, so a blast radius is a function of what happened
//     and not of when the question was asked.
//
// Every query is written to be safe under retry, because a lifecycle transition is decided
// once and may be delivered twice. That is what the idempotency ledger is for, and it is why
// the lookup and the insert are separate calls the journal sequences rather than one statement.
//
// Register a model. The eleven required fields are all present because the migration's
// constraints refuse a row missing any of them; the Go package decides *which* models
// register, and this query only records the decision.
//
// A duplicate model_id is a conflict rather than an update, and there is no ON CONFLICT
// clause: overwriting a registered model in place is the exact defect the immutability
// constraint exists to prevent, and an ON CONFLICT DO UPDATE here would quietly reintroduce
// it for whichever caller happened to use this query.
func (q *Queries) InsertModel(ctx context.Context, arg InsertModelParams) (ModelRegistry, error) {
	row := q.db.QueryRowContext(ctx, insertModel,
		arg.ModelID,
		arg.Version,
		arg.Owner,
		arg.Author,
		arg.TrainingDatasetFingerprint,
		arg.CodeRevision,
		arg.FeatureSpecification,
		arg.EvaluationResults,
		arg.Limitations,
		arg.ApprovalRecord,
		arg.DeploymentScope,
		arg.MonitoringPolicy,
		arg.RollbackArtifact,
		arg.State,
		arg.RegisteredAtUtc,
		arg.LastAuditID,
		arg.UpdatedBy,
		arg.UpdatedAtUtc,
	)
	var i ModelRegistry
	err := row.Scan(
		&i.ModelID,
		&i.Version,
		&i.Owner,
		&i.Author,
		&i.TrainingDatasetFingerprint,
		&i.CodeRevision,
		&i.FeatureSpecification,
		&i.EvaluationResults,
		&i.Limitations,
		&i.ApprovalRecord,
		&i.DeploymentScope,
		&i.MonitoringPolicy,
		&i.RollbackArtifact,
		&i.State,
		&i.RegisteredAtUtc,
		&i.LastAuditID,
		&i.UpdatedBy,
		&i.UpdatedAtUtc,
	)
	return i, err
}

const insertRevocation = `-- name: InsertRevocation :one
INSERT INTO workload_revocations (
    identity,
    model_id,
    model_version,
    revoked_at_utc,
    reason,
    evidence_ref,
    revoked_by
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING identity, model_id, model_version, revoked_at_utc, reason, evidence_ref, revoked_by
`

type InsertRevocationParams struct {
	Identity     string    `json:"identity"`
	ModelID      string    `json:"model_id"`
	ModelVersion string    `json:"model_version"`
	RevokedAtUtc time.Time `json:"revoked_at_utc"`
	Reason       string    `json:"reason"`
	EvidenceRef  string    `json:"evidence_ref"`
	RevokedBy    string    `json:"revoked_by"`
}

// Revoke an identity, permanently.
//
// reason and evidence_ref are required by the migration and are parameters here, not optional
// metadata. An unattributed revocation cannot be reviewed, and revocation is the action an
// operator disputes first, so the record has to say why and on what forensic basis.
//
// There is no update or delete path for this table, by design.
func (q *Queries) InsertRevocation(ctx context.Context, arg InsertRevocationParams) (WorkloadRevocation, error) {
	row := q.db.QueryRowContext(ctx, insertRevocation,
		arg.Identity,
		arg.ModelID,
		arg.ModelVersion,
		arg.RevokedAtUtc,
		arg.Reason,
		arg.EvidenceRef,
		arg.RevokedBy,
	)
	var i WorkloadRevocation
	err := row.Scan(
		&i.Identity,
		&i.ModelID,
		&i.ModelVersion,
		&i.RevokedAtUtc,
		&i.Reason,
		&i.EvidenceRef,
		&i.RevokedBy,
	)
	return i, err
}

const insertWorkloadIdentity = `-- name: InsertWorkloadIdentity :one
INSERT INTO workload_identities (
    identity,
    model_id,
    model_version,
    scope,
    issued_at_utc,
    expires_at_utc
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING identity, model_id, model_version, scope, issued_at_utc, expires_at_utc
`

type InsertWorkloadIdentityParams struct {
	Identity     string    `json:"identity"`
	ModelID      string    `json:"model_id"`
	ModelVersion string    `json:"model_version"`
	Scope        string    `json:"scope"`
	IssuedAtUtc  time.Time `json:"issued_at_utc"`
	ExpiresAtUtc time.Time `json:"expires_at_utc"`
}

// Issue a short-lived identity bound to one exact model and version.
//
// The expiry is a parameter rather than a database default, and the migration bounds it. A
// caller cannot mint a long-lived identity by passing a far-future expiry, which is the
// property that makes revocation meaningful: an identity cannot outlive the incident response
// that has to revoke it.
//
// An identity name that was ever revoked is refused by the trigger, so this insert cannot
// resurrect a compromised workload under a name an operator has already seen shut down.
func (q *Queries) InsertWorkloadIdentity(ctx context.Context, arg InsertWorkloadIdentityParams) (WorkloadIdentity, error) {
	row := q.db.QueryRowContext(ctx, insertWorkloadIdentity,
		arg.Identity,
		arg.ModelID,
		arg.ModelVersion,
		arg.Scope,
		arg.IssuedAtUtc,
		arg.ExpiresAtUtc,
	)
	var i WorkloadIdentity
	err := row.Scan(
		&i.Identity,
		&i.ModelID,
		&i.ModelVersion,
		&i.Scope,
		&i.IssuedAtUtc,
		&i.ExpiresAtUtc,
	)
	return i, err
}

const isIdentityRevoked = `-- name: IsIdentityRevoked :one
SELECT EXISTS (
    SELECT 1 FROM workload_revocations WHERE identity = $1
) AS revoked
`

// Whether this identity name has ever been revoked, in any model version.
//
// Scoped by identity alone, not by (identity, model, version), because the guarantee is about
// the *name*: a workload shut down as compromised must not be able to re-appear under that
// name attached to a different version. Scoping this by version would make revocation a
// property of a deployment rather than of an identity, which is the weaker and wrong claim.
func (q *Queries) IsIdentityRevoked(ctx context.Context, identity string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isIdentityRevoked, identity)
	var revoked bool
	err := row.Scan(&revoked)
	return revoked, err
}

const listActiveModels = `-- name: ListActiveModels :many
SELECT model_id, version, owner, author, training_dataset_fingerprint, code_revision, feature_specification, evaluation_results, limitations, approval_record, deployment_scope, monitoring_policy, rollback_artifact, state, registered_at_utc, last_audit_id, updated_by, updated_at_utc FROM model_registry
WHERE state NOT IN ('RETIRED', 'QUARANTINED')
ORDER BY model_id
`

// Every model still able to serve inference. Terminal states are excluded here rather than by
// the caller, because the interesting failure is a caller that forgot: retired and quarantined
// models must never appear in a serving set, and the exclusion belongs next to the schema.
func (q *Queries) ListActiveModels(ctx context.Context) ([]ModelRegistry, error) {
	rows, err := q.db.QueryContext(ctx, listActiveModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelRegistry{}
	for rows.Next() {
		var i ModelRegistry
		if err := rows.Scan(
			&i.ModelID,
			&i.Version,
			&i.Owner,
			&i.Author,
			&i.TrainingDatasetFingerprint,
			&i.CodeRevision,
			&i.FeatureSpecification,
			&i.EvaluationResults,
			&i.Limitations,
			&i.ApprovalRecord,
			&i.DeploymentScope,
			&i.MonitoringPolicy,
			&i.RollbackArtifact,
			&i.State,
			&i.RegisteredAtUtc,
			&i.LastAuditID,
			&i.UpdatedBy,
			&i.UpdatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllIdempotency = `-- name: ListAllIdempotency :many
SELECT idempotency_scope, idempotency_key, request_fingerprint, model_id, from_state, to_state, audit_id, applied_at_utc FROM model_transition_idempotency
ORDER BY model_id, applied_at_utc, idempotency_scope, idempotency_key
`

// Every transition applied to any model, oldest first.
//
// This reconstructs each model's lifecycle from recorded applications rather than from the
// current state, so a reader can see the path taken and not only where it ended up. Ordered
// oldest first because the sequence *is* the information; reversing it would make the list
// unreadable while still looking plausible.
//
// Deliberately one query for the whole ledger rather than one per model. The rehydration
// reader restores every model, so the per-model form made startup cost one round trip per
// registered model, strictly sequential, and a registry with a few thousand models then spent
// startup waiting on the network rather than reading. Ordering within a model is unchanged, so
// a caller that cares about one model's path reads the same order out of this list.
func (q *Queries) ListAllIdempotency(ctx context.Context) ([]ModelTransitionIdempotency, error) {
	rows, err := q.db.QueryContext(ctx, listAllIdempotency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelTransitionIdempotency{}
	for rows.Next() {
		var i ModelTransitionIdempotency
		if err := rows.Scan(
			&i.IdempotencyScope,
			&i.IdempotencyKey,
			&i.RequestFingerprint,
			&i.ModelID,
			&i.FromState,
			&i.ToState,
			&i.AuditID,
			&i.AppliedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllModels = `-- name: ListAllModels :many
SELECT model_id, version, owner, author, training_dataset_fingerprint, code_revision, feature_specification, evaluation_results, limitations, approval_record, deployment_scope, monitoring_policy, rollback_artifact, state, registered_at_utc, last_audit_id, updated_by, updated_at_utc FROM model_registry ORDER BY model_id
`

// Every registered model, in every lifecycle state, for startup rehydration.
//
// ListActiveModels is not a substitute. It is deliberately blind to the terminal states, which
// is correct for a serving set and exactly wrong for a restore: a journal rebuilt only from
// active models has no memory that a model was ever retired, so the model looks unregistered
// and can be registered again from scratch. Terminal states are the rows that most have to
// survive a restart.
//
// Unbounded, unlike the audit reads, because this is bounded by the number of models rather
// than by a retention period, and because a restore that silently loaded a prefix of the
// registry would be worse than one that took the whole table.
func (q *Queries) ListAllModels(ctx context.Context) ([]ModelRegistry, error) {
	rows, err := q.db.QueryContext(ctx, listAllModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelRegistry{}
	for rows.Next() {
		var i ModelRegistry
		if err := rows.Scan(
			&i.ModelID,
			&i.Version,
			&i.Owner,
			&i.Author,
			&i.TrainingDatasetFingerprint,
			&i.CodeRevision,
			&i.FeatureSpecification,
			&i.EvaluationResults,
			&i.Limitations,
			&i.ApprovalRecord,
			&i.DeploymentScope,
			&i.MonitoringPolicy,
			&i.RollbackArtifact,
			&i.State,
			&i.RegisteredAtUtc,
			&i.LastAuditID,
			&i.UpdatedBy,
			&i.UpdatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllWorkloadIdentities = `-- name: ListAllWorkloadIdentities :many
SELECT identity, model_id, model_version, scope, issued_at_utc, expires_at_utc FROM workload_identities ORDER BY identity
`

// Every workload identity ever issued, for startup rehydration.
//
// ListValidIdentitiesForModelVersion is not a substitute: it filters to currently valid ones,
// which is right for a serving check and exactly wrong for a restore, because an expired or
// revoked identity that is not loaded here becomes mintable again. The revocation check in the
// registry is a lookup in a map that only exists if the revocations were loaded too, so a
// partial load of either table silently removes a security control.
func (q *Queries) ListAllWorkloadIdentities(ctx context.Context) ([]WorkloadIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listAllWorkloadIdentities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadIdentity{}
	for rows.Next() {
		var i WorkloadIdentity
		if err := rows.Scan(
			&i.Identity,
			&i.ModelID,
			&i.ModelVersion,
			&i.Scope,
			&i.IssuedAtUtc,
			&i.ExpiresAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllWorkloadRevocations = `-- name: ListAllWorkloadRevocations :many
SELECT identity, model_id, model_version, revoked_at_utc, reason, evidence_ref, revoked_by FROM workload_revocations ORDER BY revoked_at_utc, identity
`

// Every revocation, for startup rehydration.
//
// Unbounded for the same reason as the identity list: this table is the authority on which
// identities must never be re-minted, and loading a prefix of it means the identities not
// covered by that prefix have no recorded revocation.
func (q *Queries) ListAllWorkloadRevocations(ctx context.Context) ([]WorkloadRevocation, error) {
	rows, err := q.db.QueryContext(ctx, listAllWorkloadRevocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadRevocation{}
	for rows.Next() {
		var i WorkloadRevocation
		if err := rows.Scan(
			&i.Identity,
			&i.ModelID,
			&i.ModelVersion,
			&i.RevokedAtUtc,
			&i.Reason,
			&i.EvidenceRef,
			&i.RevokedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesForModelVersion = `-- name: ListIdentitiesForModelVersion :many
SELECT identity, model_id, model_version, scope, issued_at_utc, expires_at_utc FROM workload_identities
WHERE model_id = $1 AND model_version = $2
ORDER BY identity
`

type ListIdentitiesForModelVersionParams struct {
	ModelID      string `json:"model_id"`
	ModelVersion string `json:"model_version"`
}

// Every identity currently serving one exact model version.
//
// This is the query containment widens to. It takes the model *and* the version because
// revoking only the detected workload is not containment: a compromised research worker shares
// its code and its dataset with whatever else was serving that version, and those identities
// have to be found from the store rather than from a list the responder kept in their head.
//
// Revoked identities are included, deliberately. Containment must report what it took down
// even after a restart, and a set that shrinks as revocations are processed would make the
// blast radius a function of when it was asked rather than of what happened.
func (q *Queries) ListIdentitiesForModelVersion(ctx context.Context, arg ListIdentitiesForModelVersionParams) ([]WorkloadIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listIdentitiesForModelVersion, arg.ModelID, arg.ModelVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadIdentity{}
	for rows.Next() {
		var i WorkloadIdentity
		if err := rows.Scan(
			&i.Identity,
			&i.ModelID,
			&i.ModelVersion,
			&i.Scope,
			&i.IssuedAtUtc,
			&i.ExpiresAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelAuditRefs = `-- name: ListModelAuditRefs :many
SELECT last_audit_id, state, updated_by, updated_at_utc
FROM model_registry
WHERE model_id = $1
  AND last_audit_id <> ''
ORDER BY updated_at_utc DESC
`

type ListModelAuditRefsRow struct {
	LastAuditID  string    `json:"last_audit_id"`
	State        string    `json:"state"`
	UpdatedBy    string    `json:"updated_by"`
	UpdatedAtUtc time.Time `json:"updated_at_utc"`
}

// The audit records that caused this model's current state and its immediately preceding one.
// Ordered by update time descending so a reader sees the latest cause first, which is the one
// a responder investigating a promotion needs.
func (q *Queries) ListModelAuditRefs(ctx context.Context, modelID string) ([]ListModelAuditRefsRow, error) {
	rows, err := q.db.QueryContext(ctx, listModelAuditRefs, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelAuditRefsRow{}
	for rows.Next() {
		var i ListModelAuditRefsRow
		if err := rows.Scan(
			&i.LastAuditID,
			&i.State,
			&i.UpdatedBy,
			&i.UpdatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsInState = `-- name: ListModelsInState :many
SELECT model_id, version, owner, author, training_dataset_fingerprint, code_revision, feature_specification, evaluation_results, limitations, approval_record, deployment_scope, monitoring_policy, rollback_artifact, state, registered_at_utc, last_audit_id, updated_by, updated_at_utc FROM model_registry WHERE state = $1 ORDER BY model_id
`

// The models currently in one lifecycle state, for the monitor and the reconciliation sweep.
// Ordered by model_id rather than by registration time so that two callers asking the same
// question at the same moment get the same order, which is what makes a sweep restartable.
func (q *Queries) ListModelsInState(ctx context.Context, state string) ([]ModelRegistry, error) {
	rows, err := q.db.QueryContext(ctx, listModelsInState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelRegistry{}
	for rows.Next() {
		var i ModelRegistry
		if err := rows.Scan(
			&i.ModelID,
			&i.Version,
			&i.Owner,
			&i.Author,
			&i.TrainingDatasetFingerprint,
			&i.CodeRevision,
			&i.FeatureSpecification,
			&i.EvaluationResults,
			&i.Limitations,
			&i.ApprovalRecord,
			&i.DeploymentScope,
			&i.MonitoringPolicy,
			&i.RollbackArtifact,
			&i.State,
			&i.RegisteredAtUtc,
			&i.LastAuditID,
			&i.UpdatedBy,
			&i.UpdatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevocationsForIdentityModel = `-- name: ListRevocationsForIdentityModel :many
SELECT identity, model_id, model_version, revoked_at_utc, reason, evidence_ref, revoked_by FROM workload_revocations
WHERE identity = $1
ORDER BY revoked_at_utc
`

// Every revocation for one identity, across versions. An identity that served two versions
// and was compromised in both has two rows, and an investigation needs both: the reason names
// the incident, and the version says how much surface was exposed.
func (q *Queries) ListRevocationsForIdentityModel(ctx context.Context, identity string) ([]WorkloadRevocation, error) {
	rows, err := q.db.QueryContext(ctx, listRevocationsForIdentityModel, identity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadRevocation{}
	for rows.Next() {
		var i WorkloadRevocation
		if err := rows.Scan(
			&i.Identity,
			&i.ModelID,
			&i.ModelVersion,
			&i.RevokedAtUtc,
			&i.Reason,
			&i.EvidenceRef,
			&i.RevokedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevocationsForModelVersion = `-- name: ListRevocationsForModelVersion :many
SELECT identity, model_id, model_version, revoked_at_utc, reason, evidence_ref, revoked_by FROM workload_revocations
WHERE model_id = $1 AND model_version = $2
ORDER BY revoked_at_utc, identity
`

type ListRevocationsForModelVersionParams struct {
	ModelID      string `json:"model_id"`
	ModelVersion string `json:"model_version"`
}

// The revocations recorded against one exact model version.
//
// The reported blast radius is built from these rows rather than from the live identity set,
// which is what makes containment report the same population on a retry as it did the first
// time. Reading live identities instead would make the answer depend on which revocations had
// already been written, so a retry after a partial failure would report a *smaller* blast
// radius than the first attempt -- the one outcome a compromise response must never produce.
func (q *Queries) ListRevocationsForModelVersion(ctx context.Context, arg ListRevocationsForModelVersionParams) ([]WorkloadRevocation, error) {
	rows, err := q.db.QueryContext(ctx, listRevocationsForModelVersion, arg.ModelID, arg.ModelVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadRevocation{}
	for rows.Next() {
		var i WorkloadRevocation
		if err := rows.Scan(
			&i.Identity,
			&i.ModelID,
			&i.ModelVersion,
			&i.RevokedAtUtc,
			&i.Reason,
			&i.EvidenceRef,
			&i.RevokedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidIdentitiesForModelVersion = `-- name: ListValidIdentitiesForModelVersion :many
SELECT i.identity, i.model_id, i.model_version, i.scope, i.issued_at_utc, i.expires_at_utc FROM workload_identities i
WHERE i.model_id = $1
  AND i.model_version = $2
  AND i.expires_at_utc > now()
  AND NOT EXISTS (
      SELECT 1 FROM workload_revocations r WHERE r.identity = i.identity
  )
ORDER BY i.identity
`

type ListValidIdentitiesForModelVersionParams struct {
	ModelID      string `json:"model_id"`
	ModelVersion string `json:"model_version"`
}

// The same set, restricted to identities not yet revoked and not yet expired.
//
// Separate from ListIdentitiesForModelVersion on purpose. Containment wants the full set
// (assertion 31 and the widening path); a serving check wants only the identities that may
// still act. Collapsing them would mean either reporting fewer revocations than happened or
// admitting revoked identities as usable, and both are worse than a second query.
func (q *Queries) ListValidIdentitiesForModelVersion(ctx context.Context, arg ListValidIdentitiesForModelVersionParams) ([]WorkloadIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listValidIdentitiesForModelVersion, arg.ModelID, arg.ModelVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadIdentity{}
	for rows.Next() {
		var i WorkloadIdentity
		if err := rows.Scan(
			&i.Identity,
			&i.ModelID,
			&i.ModelVersion,
			&i.Scope,
			&i.IssuedAtUtc,
			&i.ExpiresAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTransitionIdempotency = `-- name: RecordTransitionIdempotency :one
INSERT INTO model_transition_idempotency (
    idempotency_scope,
    idempotency_key,
    request_fingerprint,
    model_id,
    from_state,
    to_state,
    audit_id,
    applied_at_utc
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING idempotency_scope, idempotency_key, request_fingerprint, model_id, from_state, to_state, audit_id, applied_at_utc
`

type RecordTransitionIdempotencyParams struct {
	IdempotencyScope   string    `json:"idempotency_scope"`
	IdempotencyKey     string    `json:"idempotency_key"`
	RequestFingerprint string    `json:"request_fingerprint"`
	ModelID            string    `json:"model_id"`
	FromState          string    `json:"from_state"`
	ToState            string    `json:"to_state"`
	AuditID            string    `json:"audit_id"`
	AppliedAtUtc       time.Time `json:"applied_at_utc"`
}

// Record that a transition has been applied.
//
// The primary key on (idempotency_scope, idempotency_key) is the concurrency control. Two
// concurrent retries of the same transition race here, one wins, and the loser gets a unique
// violation rather than a second application. This is why the insert exists as its own call
// after the state write rather than being folded into it: a single statement cannot distinguish
// "applied by me" from "applied by a concurrent retry of mine", and guessing wrong either
// applies a transition twice or hides one that was applied.
//
// The caller supplies request_fingerprint. A retry carrying a *different* fingerprint under
// the same key is a different request that collided with an idempotency key, which the journal
// must surface rather than treat as a retry of the first.
func (q *Queries) RecordTransitionIdempotency(ctx context.Context, arg RecordTransitionIdempotencyParams) (ModelTransitionIdempotency, error) {
	row := q.db.QueryRowContext(ctx, recordTransitionIdempotency,
		arg.IdempotencyScope,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.ModelID,
		arg.FromState,
		arg.ToState,
		arg.AuditID,
		arg.AppliedAtUtc,
	)
	var i ModelTransitionIdempotency
	err := row.Scan(
		&i.IdempotencyScope,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.ModelID,
		&i.FromState,
		&i.ToState,
		&i.AuditID,
		&i.AppliedAtUtc,
	)
	return i, err
}

const setModelState = `-- name: SetModelState :one
UPDATE model_registry
SET state = $2,
    last_audit_id = $3,
    updated_by = $4,
    updated_at_utc = $5
WHERE model_id = $1
RETURNING model_id, version, owner, author, training_dataset_fingerprint, code_revision, feature_specification, evaluation_results, limitations, approval_record, deployment_scope, monitoring_policy, rollback_artifact, state, registered_at_utc, last_audit_id, updated_by, updated_at_utc
`

type SetModelStateParams struct {
	ModelID      string    `json:"model_id"`
	State        string    `json:"state"`
	LastAuditID  string    `json:"last_audit_id"`
	UpdatedBy    string    `json:"updated_by"`
	UpdatedAtUtc time.Time `json:"updated_at_utc"`
}

// Record a lifecycle transition.
//
// Two columns move together and deliberately. last_audit_id is not a default that a caller may
// omit: the migration refuses a state change that cites no audit record, so a transition whose
// cause was not recorded cannot be stored even if the caller wanted to store it. Making the
// audit identifier a required parameter is what keeps that guarantee from depending on every
// caller remembering it.
//
// The transition's legality is enforced by the trigger, not by this query. The Go package
// decides; the database refuses anything the package would have refused, so a second writer
// cannot produce a state no evaluator would have produced.
func (q *Queries) SetModelState(ctx context.Context, arg SetModelStateParams) (ModelRegistry, error) {
	row := q.db.QueryRowContext(ctx, setModelState,
		arg.ModelID,
		arg.State,
		arg.LastAuditID,
		arg.UpdatedBy,
		arg.UpdatedAtUtc,
	)
	var i ModelRegistry
	err := row.Scan(
		&i.ModelID,
		&i.Version,
		&i.Owner,
		&i.Author,
		&i.TrainingDatasetFingerprint,
		&i.CodeRevision,
		&i.FeatureSpecification,
		&i.EvaluationResults,
		&i.Limitations,
		&i.ApprovalRecord,
		&i.DeploymentScope,
		&i.MonitoringPolicy,
		&i.RollbackArtifact,
		&i.State,
		&i.RegisteredAtUtc,
		&i.LastAuditID,
		&i.UpdatedBy,
		&i.UpdatedAtUtc,
	)
	return i, err
}
