// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AuditCheckpoint struct {
	Partition     string    `json:"partition"`
	FirstSequence int64     `json:"first_sequence"`
	LastSequence  int64     `json:"last_sequence"`
	FirstHash     []byte    `json:"first_hash"`
	LastHash      []byte    `json:"last_hash"`
	RecordCount   int32     `json:"record_count"`
	CreatedAtUtc  time.Time `json:"created_at_utc"`
	SigningKeyID  string    `json:"signing_key_id"`
	Signature     []byte    `json:"signature"`
	SchemaVersion int32     `json:"schema_version"`
}

type AuditDeletionEvent struct {
	AuditID       string    `json:"audit_id"`
	Partition     string    `json:"partition"`
	FirstSequence int64     `json:"first_sequence"`
	LastSequence  int64     `json:"last_sequence"`
	RequestedBy   string    `json:"requested_by"`
	ApprovedBy    string    `json:"approved_by"`
	DeletedAtUtc  time.Time `json:"deleted_at_utc"`
}

type AuditRecord struct {
	AuditID       string    `json:"audit_id"`
	Partition     string    `json:"partition"`
	Sequence      int64     `json:"sequence"`
	ActorID       string    `json:"actor_id"`
	ActorType     string    `json:"actor_type"`
	Action        string    `json:"action"`
	TargetType    string    `json:"target_type"`
	TargetID      string    `json:"target_id"`
	Environment   string    `json:"environment"`
	MarketScope   string    `json:"market_scope"`
	OccurredAtUtc time.Time `json:"occurred_at_utc"`
	RecordedAtUtc time.Time `json:"recorded_at_utc"`
	Reason        string    `json:"reason"`
	CorrelationID string    `json:"correlation_id"`
	CausationID   string    `json:"causation_id"`
	PolicyVersion string    `json:"policy_version"`
	Result        string    `json:"result"`
	BeforeDigest  string    `json:"before_digest"`
	AfterDigest   string    `json:"after_digest"`
	PreviousHash  []byte    `json:"previous_hash"`
	RecordHash    []byte    `json:"record_hash"`
	SigningKeyID  string    `json:"signing_key_id"`
	SchemaVersion int32     `json:"schema_version"`
}

type AuthzApproval struct {
	RequestID     string       `json:"request_id"`
	DiffDigest    string       `json:"diff_digest"`
	RequestedBy   string       `json:"requested_by"`
	ApprovedBy    string       `json:"approved_by"`
	ApprovedAtUtc time.Time    `json:"approved_at_utc"`
	ExpiresAtUtc  time.Time    `json:"expires_at_utc"`
	PolicyVersion string       `json:"policy_version"`
	AppliedAtUtc  sql.NullTime `json:"applied_at_utc"`
}

type AuthzDecision struct {
	DecisionID         string    `json:"decision_id"`
	CommandID          string    `json:"command_id"`
	ActorID            string    `json:"actor_id"`
	ActorType          string    `json:"actor_type"`
	Action             string    `json:"action"`
	Environment        string    `json:"environment"`
	Allowed            bool      `json:"allowed"`
	RefusalCode        string    `json:"refusal_code"`
	Reason             string    `json:"reason"`
	PolicyBundleDigest string    `json:"policy_bundle_digest"`
	DecidedAtUtc       time.Time `json:"decided_at_utc"`
}

type AuthzPermissionState struct {
	StateID         int32     `json:"state_id"`
	CurrentRevision int32     `json:"current_revision"`
	UpdatedAtUtc    time.Time `json:"updated_at_utc"`
}

type AuthzPolicyBundle struct {
	Digest         string          `json:"digest"`
	Rules          json.RawMessage `json:"rules"`
	SchemaVersion  int32           `json:"schema_version"`
	CreatedAtUtc   time.Time       `json:"created_at_utc"`
	ActivatedAtUtc time.Time       `json:"activated_at_utc"`
	RetiredAtUtc   sql.NullTime    `json:"retired_at_utc"`
}

type AuthzRoleActionExclusion struct {
	Role   string `json:"role"`
	Action string `json:"action"`
}

type AuthzRoleGrant struct {
	GrantID      string         `json:"grant_id"`
	SubjectID    string         `json:"subject_id"`
	SubjectType  string         `json:"subject_type"`
	Role         string         `json:"role"`
	Markets      []string       `json:"markets"`
	Accounts     []string       `json:"accounts"`
	Environments []string       `json:"environments"`
	GrantedAtUtc time.Time      `json:"granted_at_utc"`
	ExpiresAtUtc time.Time      `json:"expires_at_utc"`
	ApprovedBy   string         `json:"approved_by"`
	RevokedAtUtc sql.NullTime   `json:"revoked_at_utc"`
	RevokedBy    sql.NullString `json:"revoked_by"`
}

type AuthzSession struct {
	SessionID          string         `json:"session_id"`
	SubjectID          string         `json:"subject_id"`
	SessionClass       string         `json:"session_class"`
	AuthenticatedAtUtc time.Time      `json:"authenticated_at_utc"`
	LastActiveAtUtc    time.Time      `json:"last_active_at_utc"`
	AuthStrength       string         `json:"auth_strength"`
	StepUpAtUtc        sql.NullTime   `json:"step_up_at_utc"`
	PermissionRevision int32          `json:"permission_revision"`
	RevokedAtUtc       sql.NullTime   `json:"revoked_at_utc"`
	RevokedReason      sql.NullString `json:"revoked_reason"`
}

type AuthzSessionPolicy struct {
	SessionClass       string `json:"session_class"`
	IdleTimeoutSec     int32  `json:"idle_timeout_sec"`
	AbsoluteTimeoutSec int32  `json:"absolute_timeout_sec"`
	StepUpFreshnessSec int32  `json:"step_up_freshness_sec"`
}

// One balanced posting set. Rows are immutable; the ledger_entry_is_append_only trigger refuses UPDATE and DELETE.
type LedgerEntry struct {
	EntryID         string         `json:"entry_id"`
	SequenceNo      int64          `json:"sequence_no"`
	SourceCommandID string         `json:"source_command_id"`
	CorrelationID   string         `json:"correlation_id"`
	CorrectsEntryID sql.NullString `json:"corrects_entry_id"`
	Reason          sql.NullString `json:"reason"`
	PostedAt        time.Time      `json:"posted_at"`
	IdempotencyKey  string         `json:"idempotency_key"`
	ContentHash     []byte         `json:"content_hash"`
}

// One double-entry leg. Entries must balance per asset, enforced by entry_must_balance.
type LedgerLine struct {
	EntryID   string `json:"entry_id"`
	LineNo    int32  `json:"line_no"`
	Account   string `json:"account"`
	Subject   string `json:"subject"`
	Asset     string `json:"asset"`
	Direction string `json:"direction"`
	Amount    string `json:"amount"`
}

type ModelRegistry struct {
	ModelID                    string    `json:"model_id"`
	Version                    string    `json:"version"`
	Owner                      string    `json:"owner"`
	Author                     string    `json:"author"`
	TrainingDatasetFingerprint string    `json:"training_dataset_fingerprint"`
	CodeRevision               string    `json:"code_revision"`
	FeatureSpecification       string    `json:"feature_specification"`
	EvaluationResults          string    `json:"evaluation_results"`
	Limitations                string    `json:"limitations"`
	ApprovalRecord             string    `json:"approval_record"`
	DeploymentScope            string    `json:"deployment_scope"`
	MonitoringPolicy           string    `json:"monitoring_policy"`
	RollbackArtifact           string    `json:"rollback_artifact"`
	State                      string    `json:"state"`
	RegisteredAtUtc            time.Time `json:"registered_at_utc"`
	LastAuditID                string    `json:"last_audit_id"`
	UpdatedBy                  string    `json:"updated_by"`
	UpdatedAtUtc               time.Time `json:"updated_at_utc"`
}

type ModelTransitionIdempotency struct {
	IdempotencyScope   string    `json:"idempotency_scope"`
	IdempotencyKey     string    `json:"idempotency_key"`
	RequestFingerprint string    `json:"request_fingerprint"`
	ModelID            string    `json:"model_id"`
	FromState          string    `json:"from_state"`
	ToState            string    `json:"to_state"`
	AuditID            string    `json:"audit_id"`
	AppliedAtUtc       time.Time `json:"applied_at_utc"`
}

type WorkloadIdentity struct {
	Identity     string    `json:"identity"`
	ModelID      string    `json:"model_id"`
	ModelVersion string    `json:"model_version"`
	Scope        string    `json:"scope"`
	IssuedAtUtc  time.Time `json:"issued_at_utc"`
	ExpiresAtUtc time.Time `json:"expires_at_utc"`
}

type WorkloadRevocation struct {
	Identity     string    `json:"identity"`
	ModelID      string    `json:"model_id"`
	ModelVersion string    `json:"model_version"`
	RevokedAtUtc time.Time `json:"revoked_at_utc"`
	Reason       string    `json:"reason"`
	EvidenceRef  string    `json:"evidence_ref"`
	RevokedBy    string    `json:"revoked_by"`
}
