// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	AppendAuditCheckpoint(ctx context.Context, arg AppendAuditCheckpointParams) (AuditCheckpoint, error)
	//
	// The append-only evidence write.
	//
	// There is no ON CONFLICT clause here, deliberately. A duplicate audit_id is a genuine
	// conflict between two different facts, and silently returning the existing row would make
	// the second write disappear while the caller believed it was recorded. The ledger is
	// idempotent because a repeat is a retry; an audit record is idempotent because a repeat is
	// a contradiction, and those are different situations that happen to look alike.
	AppendAuditRecord(ctx context.Context, arg AppendAuditRecordParams) (AuditRecord, error)
	//
	// The entry header for one posting set.
	//
	// Idempotent rather than erroring on a repeat, because a retried command must not create a
	// second financial fact.
	//
	// The conflict target is the PAIR (source_command_id, idempotency_key), because that is what
	// the unique index covers: entry_idempotency_uniq is on the pair, not on the key alone, since
	// the same key issued under a different command is a different posting and collapsing them
	// would lose a financial fact. Writing ON CONFLICT (idempotency_key) looks equivalent and is
	// not -- it has no matching unique index, so the statement fails at runtime with "there is no
	// unique or exclusion constraint matching the ON CONFLICT specification". Neither sqlc nor
	// sqlc vet catches that, which is why scripts/rehearse_migrations.py executes every query
	// against the real schema.
	AppendEntry(ctx context.Context, arg AppendEntryParams) (LedgerEntry, error)
	//
	// The per-asset balance check, computed rather than read.
	//
	// This is the query the reconciliation path uses to decide whether a posting set is a valid
	// correction or a defect. The constraint makes the database refuse an unbalanced entry; this
	// makes the application able to explain one without reproducing the trigger's logic.
	CheckEntryBalances(ctx context.Context, entryID string) (CheckEntryBalancesRow, error)
	GetAuditRecord(ctx context.Context, auditID string) (AuditRecord, error)
	GetEntry(ctx context.Context, entryID string) (LedgerEntry, error)
	//
	// Takes both halves of the pair for the same reason AppendEntry does. Looking up by the key
	// alone would return an arbitrary posting among every command that reused the key, which is
	// exactly the ambiguity the unique index exists to prevent.
	GetEntryByIdempotencyKey(ctx context.Context, arg GetEntryByIdempotencyKeyParams) (LedgerEntry, error)
	GetLastAuditRecordInPartition(ctx context.Context, partition string) (AuditRecord, error)
	GetLatestAuditCheckpoint(ctx context.Context, partition string) (AuditCheckpoint, error)
	GetModel(ctx context.Context, modelID string) (ModelRegistry, error)
	//
	// The next sequence number for a partition.
	//
	// Computed as max + 1 rather than read from a counter table so that the number is always
	// derived from the chain that actually exists. A counter table can disagree with the records
	// after a restore, and a gap detected only at verification time is a gap that has already
	// been written to.
	GetNextAuditSequence(ctx context.Context, partition string) (int32, error)
	GetRevocation(ctx context.Context, identity string) (WorkloadRevocation, error)
	//
	// The transition previously applied under this scope and key, if any.
	//
	// The journal calls this before deciding to apply, and its absence is what tells the journal
	// this is a first attempt rather than a retry.
	GetTransitionIdempotency(ctx context.Context, arg GetTransitionIdempotencyParams) (ModelTransitionIdempotency, error)
	GetWorkloadIdentity(ctx context.Context, identity string) (WorkloadIdentity, error)
	InsertAuditDeletionEvent(ctx context.Context, arg InsertAuditDeletionEventParams) (AuditDeletionEvent, error)
	//
	// The caller inserts the header and then its legs. There is no single statement that writes
	// both, because the balance trigger is deferred to the end of the transaction: a set that
	// does not balance is refused at COMMIT rather than half-written. That deferral is the point,
	// so the legs are written by a separate statement rather than a CTE.
	InsertLine(ctx context.Context, arg InsertLineParams) error
	// Queries against the model registry, the workload identities that may serve it, the
	// revocations that stop them, and the idempotency ledger.
	//
	// Authority, and why these queries are shaped the way they are.
	//
	// The Go package in services/control-plane/model decides; these queries only persist what it
	// decided. Nothing here is allowed to become a second decision path, and the shapes below are
	// chosen to make that structurally difficult rather than merely documented:
	//
	//   * There is no UPDATE that can move a model between arbitrary states. The only state query
	//     writes the target state alongside the audit record that caused it, so a caller cannot
	//     produce a state whose origin is not in the audit chain.
	//   * There is no DELETE anywhere in this file. The three tables that must not lose a row
	//     (revocations, the idempotency ledger, and the registry itself) are protected by triggers
	//     in the migration; a query that asked to delete one would fail at runtime, and its absence
	//     here means nobody writes code expecting it to work.
	//   * The revocation queries answer containment questions by reading recorded revocations
	//     rather than by reading live identities, so a blast radius is a function of what happened
	//     and not of when the question was asked.
	//
	// Every query is written to be safe under retry, because a lifecycle transition is decided
	// once and may be delivered twice. That is what the idempotency ledger is for, and it is why
	// the lookup and the insert are separate calls the journal sequences rather than one statement.
	//
	// Register a model. The eleven required fields are all present because the migration's
	// constraints refuse a row missing any of them; the Go package decides *which* models
	// register, and this query only records the decision.
	//
	// A duplicate model_id is a conflict rather than an update, and there is no ON CONFLICT
	// clause: overwriting a registered model in place is the exact defect the immutability
	// constraint exists to prevent, and an ON CONFLICT DO UPDATE here would quietly reintroduce
	// it for whichever caller happened to use this query.
	InsertModel(ctx context.Context, arg InsertModelParams) (ModelRegistry, error)
	//
	// Revoke an identity, permanently.
	//
	// reason and evidence_ref are required by the migration and are parameters here, not optional
	// metadata. An unattributed revocation cannot be reviewed, and revocation is the action an
	// operator disputes first, so the record has to say why and on what forensic basis.
	//
	// There is no update or delete path for this table, by design.
	InsertRevocation(ctx context.Context, arg InsertRevocationParams) (WorkloadRevocation, error)
	//
	// Issue a short-lived identity bound to one exact model and version.
	//
	// The expiry is a parameter rather than a database default, and the migration bounds it. A
	// caller cannot mint a long-lived identity by passing a far-future expiry, which is the
	// property that makes revocation meaningful: an identity cannot outlive the incident response
	// that has to revoke it.
	//
	// An identity name that was ever revoked is refused by the trigger, so this insert cannot
	// resurrect a compromised workload under a name an operator has already seen shut down.
	InsertWorkloadIdentity(ctx context.Context, arg InsertWorkloadIdentityParams) (WorkloadIdentity, error)
	//
	// Whether this identity name has ever been revoked, in any model version.
	//
	// Scoped by identity alone, not by (identity, model, version), because the guarantee is about
	// the *name*: a workload shut down as compromised must not be able to re-appear under that
	// name attached to a different version. Scoping this by version would make revocation a
	// property of a deployment rather than of an identity, which is the weaker and wrong claim.
	IsIdentityRevoked(ctx context.Context, identity string) (bool, error)
	//
	// Every model still able to serve inference. Terminal states are excluded here rather than by
	// the caller, because the interesting failure is a caller that forgot: retired and quarantined
	// models must never appear in a serving set, and the exclusion belongs next to the schema.
	ListActiveModels(ctx context.Context) ([]ModelRegistry, error)
	//
	// Every registered model, in every lifecycle state, for startup rehydration.
	//
	// ListActiveModels is not a substitute. It is deliberately blind to the terminal states, which
	// is correct for a serving set and exactly wrong for a restore: a journal rebuilt only from
	// active models has no memory that a model was ever retired, so the model looks unregistered
	// and can be registered again from scratch. Terminal states are the rows that most have to
	// survive a restart.
	//
	// Unbounded, unlike the audit reads, because this is bounded by the number of models rather
	// than by a retention period, and because a restore that silently loaded a prefix of the
	// registry would be worse than one that took the whole table.
	ListAllModels(ctx context.Context) ([]ModelRegistry, error)
	//
	// Every workload identity ever issued, for startup rehydration.
	//
	// ListValidIdentitiesForModelVersion is not a substitute: it filters to currently valid ones,
	// which is right for a serving check and exactly wrong for a restore, because an expired or
	// revoked identity that is not loaded here becomes mintable again. The revocation check in the
	// registry is a lookup in a map that only exists if the revocations were loaded too, so a
	// partial load of either table silently removes a security control.
	ListAllWorkloadIdentities(ctx context.Context) ([]WorkloadIdentity, error)
	//
	// Every revocation, for startup rehydration.
	//
	// Unbounded for the same reason as the identity list: this table is the authority on which
	// identities must never be re-minted, and loading a prefix of it means the identities not
	// covered by that prefix have no recorded revocation.
	ListAllWorkloadRevocations(ctx context.Context) ([]WorkloadRevocation, error)
	//
	// The retained record of a deletion. Deleting evidence is permitted under a two-person
	// approval after expiry, and the fact that it happened is itself kept, so this table is
	// append-only in the same way the evidence it describes is.
	ListAuditDeletionEvents(ctx context.Context, limit int32) ([]AuditDeletionEvent, error)
	ListAuditRecordsByCorrelation(ctx context.Context, correlationID string) ([]AuditRecord, error)
	//
	// Bounded on purpose. An unbounded actor history is a table scan over the evidence that has
	// to survive for seven years, and the callers that need it are investigations rather than
	// request handlers.
	ListAuditRecordsForActor(ctx context.Context, arg ListAuditRecordsForActorParams) ([]AuditRecord, error)
	ListAuditRecordsInPartitionRange(ctx context.Context, arg ListAuditRecordsInPartitionRangeParams) ([]AuditRecord, error)
	ListCorrectionsForEntry(ctx context.Context, correctsEntryID sql.NullString) ([]LedgerEntry, error)
	ListEntriesByCorrelation(ctx context.Context, correlationID string) ([]LedgerEntry, error)
	//
	// Every transition applied to one model, oldest first.
	//
	// This reconstructs the model's lifecycle from recorded applications rather than from the
	// current state, so a reader can see the path taken and not only where it ended up. Ordered
	// oldest first because the sequence *is* the information; reversing it would make the list
	// unreadable while still looking plausible.
	ListIdempotencyForModel(ctx context.Context, modelID string) ([]ModelTransitionIdempotency, error)
	//
	// Every identity currently serving one exact model version.
	//
	// This is the query containment widens to. It takes the model *and* the version because
	// revoking only the detected workload is not containment: a compromised research worker shares
	// its code and its dataset with whatever else was serving that version, and those identities
	// have to be found from the store rather than from a list the responder kept in their head.
	//
	// Revoked identities are included, deliberately. Containment must report what it took down
	// even after a restart, and a set that shrinks as revocations are processed would make the
	// blast radius a function of when it was asked rather than of what happened.
	ListIdentitiesForModelVersion(ctx context.Context, arg ListIdentitiesForModelVersionParams) ([]WorkloadIdentity, error)
	ListLinesForEntry(ctx context.Context, entryID string) ([]LedgerLine, error)
	//
	// The audit records that caused this model's current state and its immediately preceding one.
	// Ordered by update time descending so a reader sees the latest cause first, which is the one
	// a responder investigating a promotion needs.
	ListModelAuditRefs(ctx context.Context, modelID string) ([]ListModelAuditRefsRow, error)
	//
	// The models currently in one lifecycle state, for the monitor and the reconciliation sweep.
	// Ordered by model_id rather than by registration time so that two callers asking the same
	// question at the same moment get the same order, which is what makes a sweep restartable.
	ListModelsInState(ctx context.Context, state string) ([]ModelRegistry, error)
	//
	// Every revocation for one identity, across versions. An identity that served two versions
	// and was compromised in both has two rows, and an investigation needs both: the reason names
	// the incident, and the version says how much surface was exposed.
	ListRevocationsForIdentityModel(ctx context.Context, identity string) ([]WorkloadRevocation, error)
	//
	// The revocations recorded against one exact model version.
	//
	// The reported blast radius is built from these rows rather than from the live identity set,
	// which is what makes containment report the same population on a retry as it did the first
	// time. Reading live identities instead would make the answer depend on which revocations had
	// already been written, so a retry after a partial failure would report a *smaller* blast
	// radius than the first attempt -- the one outcome a compromise response must never produce.
	ListRevocationsForModelVersion(ctx context.Context, arg ListRevocationsForModelVersionParams) ([]WorkloadRevocation, error)
	//
	// The same set, restricted to identities not yet revoked and not yet expired.
	//
	// Separate from ListIdentitiesForModelVersion on purpose. Containment wants the full set
	// (assertion 31 and the widening path); a serving check wants only the identities that may
	// still act. Collapsing them would mean either reporting fewer revocations than happened or
	// admitting revoked identities as usable, and both are worse than a second query.
	ListValidIdentitiesForModelVersion(ctx context.Context, arg ListValidIdentitiesForModelVersionParams) ([]WorkloadIdentity, error)
	//
	// Record that a transition has been applied.
	//
	// The primary key on (idempotency_scope, idempotency_key) is the concurrency control. Two
	// concurrent retries of the same transition race here, one wins, and the loser gets a unique
	// violation rather than a second application. This is why the insert exists as its own call
	// after the state write rather than being folded into it: a single statement cannot distinguish
	// "applied by me" from "applied by a concurrent retry of mine", and guessing wrong either
	// applies a transition twice or hides one that was applied.
	//
	// The caller supplies request_fingerprint. A retry carrying a *different* fingerprint under
	// the same key is a different request that collided with an idempotency key, which the journal
	// must surface rather than treat as a retry of the first.
	RecordTransitionIdempotency(ctx context.Context, arg RecordTransitionIdempotencyParams) (ModelTransitionIdempotency, error)
	//
	// Record a lifecycle transition.
	//
	// Two columns move together and deliberately. last_audit_id is not a default that a caller may
	// omit: the migration refuses a state change that cites no audit record, so a transition whose
	// cause was not recorded cannot be stored even if the caller wanted to store it. Making the
	// audit identifier a required parameter is what keeps that guarantee from depending on every
	// caller remembering it.
	//
	// The transition's legality is enforced by the trigger, not by this query. The Go package
	// decides; the database refuses anything the package would have refused, so a second writer
	// cannot produce a state no evaluator would have produced.
	SetModelState(ctx context.Context, arg SetModelStateParams) (ModelRegistry, error)
}

var _ Querier = (*Queries)(nil)
