"""The G5 gate report must describe the current tree.

The report at evidence/gates/G5-gate-report.json is what a reviewer reads to decide that the G5
gate passed. It carries a verdict and a per-criterion `mechanically_verified` flag, which together
assert something strong: the criteria were established by running checks, not by argument.

That assertion was not tied to the tree it described. The report was generated by hand and
regenerated by hand, and nothing failed when the code moved on. Every digest in it was correct
when written and went stale silently, while the report kept saying PASS. A reviewer reading it
months later would have no way to tell it described an older tree.

This is the same defect the `sqlc is up to date` step catches for generated Go code - a tracked
artifact that must match a generator, with no check tying the two together - applied to a
governance artifact, where it is worse because the failure is invisible and the artifact is
trusted.

The check is byte-for-byte against a full regeneration rather than a digest recomputation, so it
also catches a hand-edited verdict: a report whose content no longer matches what the generator
produces is stale regardless of whether its digests still happen to be correct. That case is the
one a digest-only check would miss completely, and it is the one that matters most for a document
whose whole purpose is to be believed.

Possible only because the report is deterministic: its `executed_at` is a constant in the
generator, not a clock read. A report embedding the current time could never be checked.

Run:
    python -m pytest tests/ci -q
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR = REPO_ROOT / "scripts" / "generate_g5_gate_report.py"


def test_the_g5_gate_report_matches_the_current_tree() -> None:
    """The committed G5 report must be exactly what the generator produces now."""
    if not GENERATOR.is_file():
        # The check is a real control, so its absence is a failure rather than a silent pass.
        # A check that quietly stops running is the failure mode this repository keeps recording.
        raise AssertionError(
            f"{GENERATOR} is not present; the G5 report can no longer be verified against the "
            "tree, and nothing would fail if it went stale"
        )

    result = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, (
        "the G5 gate report does not match the current tree; regenerate and commit it:\n"
        f"{result.stdout.strip()}\n{result.stderr.strip()}"
    )
