#!/usr/bin/env python3
"""Refuse SQL string literals in the Go layer outside the generated package and the migrator.

sqlc.yaml states the rule and credits tests/ci with enforcing it. Tests/ci did not enforce it: the
comment was the only place the rule existed, which is the defect class this repository has now
recorded five times in five different files - a control asserted in prose rather than in code, green
because nothing checked it.

Why the rule exists at all: generated accessors are the only sanctioned way for Go to reach
PostgreSQL, because hand-written SQL in a Go string does not have to agree with the schema. A
constraint the database enforces quietly stops being enforced the moment one query moves into a
string literal, and nothing in sqlc, the Go build or `go vet` sees that happen.

The exemptions are narrow, named, and each carries a reason that has to keep being true:

  * `services/control-plane/db/dbgen` - generated. It is SQL turned into Go by the tool that read
    the schema, so a literal there is the output of the check rather than a bypass of it.
  * `services/control-plane/migrate/store.go` - the migrator's own bookkeeping table. The migrator
    records which migrations it has applied, and it has to do that while applying the others; the
    table belongs to the module that writes it and no generated accessor covers it.

Run:  python scripts/check_no_stray_sql.py
Exit: 0 clean, 1 one or more violations, 2 the check could not run.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

GENERATED_PACKAGE = "services/control-plane/db/dbgen"

# Path -> why it is exempt. A bare path with no reason is a bypass with a comment attached, so the
# reason is part of the data rather than of the code that reads it: adding an entry is one line and
# one sentence, which is the smallest possible unit of deliberate bypass.
EXEMPT: dict[str, str] = {
    GENERATED_PACKAGE: "generated by sqlc from the schema; the tool that enforces the rule emits it",
    "services/control-plane/migrate/store.go": (
        "the migrator's own applied_set bookkeeping, written by the module that owns it and "
        "covered by no generated accessor"
    ),
    "services/control-plane/migrate/store_sql.go": (
        "the migrator's own SQL constants, including the advisory-lock pair. A lock is a session "
        "primitive rather than a table access, so no generated accessor can express it, and the "
        "migrator must hold it before the schema under migration is known to exist"
    ),
}

# Statement shapes rather than bare keywords. `SELECT` alone would match prose and Go identifiers;
# matching the statement plus what follows it catches a query written across lines, in any case,
# with any amount of whitespace - which a keyword-only pattern does not, and a keyword-only pattern
# is what a reader assumes is being used here.
#
# The two patterns that span two keywords are tempered so they cannot cross a statement boundary.
# An untempered `SELECT ... FROM` with a 400-character window matches `SELECT pg_advisory_lock($1)`
# by finding the FROM of whatever statement follows it, and this file reported exactly that - a
# false positive in the checker, found by running it against the tree rather than against a sample.
# A gate that cries wolf on an existing file gets ignored on the day it is right.
_NOT_A_BOUNDARY = r"(?:(?![;`\"'])[^\n])"
_STATEMENTS = (
    ("INSERT INTO", re.compile(r"\bINSERT\s+INTO\b", re.IGNORECASE)),
    ("UPDATE ... SET", re.compile(r"\bUPDATE\s+[\w.\"]+\s+SET\b", re.IGNORECASE)),
    ("DELETE FROM", re.compile(r"\bDELETE\s+FROM\b", re.IGNORECASE)),
    (
        "SELECT ... FROM",
        re.compile(rf"\bSELECT\b(?:{_NOT_A_BOUNDARY}{{0,400}}?)\bFROM\b", re.IGNORECASE),
    ),
    ("CREATE TABLE", re.compile(r"\bCREATE\s+(?:UNLOGGED\s+)?TABLE\b", re.IGNORECASE)),
    ("CREATE INDEX", re.compile(r"\bCREATE\s+(?:UNIQUE\s+)?INDEX\b", re.IGNORECASE)),
    ("DROP TABLE", re.compile(r"\bDROP\s+TABLE\b", re.IGNORECASE)),
    ("ALTER TABLE", re.compile(r"\bALTER\s+TABLE\b", re.IGNORECASE)),
    (
        "GRANT / REVOKE",
        re.compile(rf"\b(?:GRANT|REVOKE)\b(?:{_NOT_A_BOUNDARY}{{0,80}}?)\bON\b", re.IGNORECASE),
    ),
    # The gap the other shapes leave, found by running this against the tree rather than by
    # reasoning about it: `SELECT pg_advisory_lock($1)` is a query with no FROM, so none of the nine
    # shapes above match it and it passed. Enumerating statement shapes cannot close that - there
    # are more of them than anyone enumerates, and each one added is a hole until it is needed.
    #
    # A bind placeholder inside a Go string is the signal instead. `$1` is not English, is not a Go
    # format verb, and does not appear in this repository's error messages, so requiring a SQL
    # keyword and a placeholder in the same statement catches the shapes nobody wrote down without
    # matching prose. The window is tempered on the same boundaries, so it cannot reach from one
    # statement into the next.
    (
        "SQL statement with a bind placeholder",
        re.compile(
            rf"\b(?:SELECT|INSERT|UPDATE|DELETE|WITH|MERGE)\b(?:{_NOT_A_BOUNDARY}{{0,200}}?)\$\d",
            re.IGNORECASE,
        ),
    ),
)

# Go source that is not application code. _test.go files are excluded because a test that needs a
# fixture table legitimately spells the DDL out, and a test cannot mutate authoritative state.
_PATH_SKIP = re.compile(r"_test\.go$")


def go_files() -> list[Path]:
    listed = subprocess.run(
        ["git", "ls-files", "-z", "*.go"],
        cwd=ROOT,
        capture_output=True,
        check=True,
    )
    return [
        ROOT / name
        for name in listed.stdout.decode("utf-8").split("\0")
        if name and not _PATH_SKIP.search(name)
    ]


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def exempt_reason(name: str) -> str | None:
    if name == GENERATED_PACKAGE or name.startswith(GENERATED_PACKAGE + "/"):
        return EXEMPT[GENERATED_PACKAGE]
    return EXEMPT.get(name)


def violations_in(path: Path) -> list[tuple[int, str, str]]:
    """Every statement-shaped literal in *path* as (line number, shape, line text).

    The whole file is scanned rather than line by line, because a query written across lines is
    ordinary: gofmt reflows a long SQL string, and an editor wraps it. A per-line scan is defeated by
    the formatter, which means it would report clean on a tree where a reviewer can plainly see the
    query - the green-while-wrong direction this check exists to prevent.

    The comment exclusion is applied by position rather than by pre-filtering lines, so it survives
    the same wrapping: a match that starts inside a `//` comment is documentation and is skipped,
    and one that starts in code is not.
    """
    text = path.read_text(encoding="utf-8")

    def line_start(offset: int) -> int:
        return text.rfind("\n", 0, offset) + 1

    comment_spans = [
        (m.start(), m.end()) for m in re.finditer(r"//[^\n]*", text)
    ]

    def in_comment(start: int) -> bool:
        return any(begin <= start < end for begin, end in comment_spans)

    lines = text.splitlines()
    hits: list[tuple[int, str, str]] = []
    claimed: set[int] = set()
    for shape, pattern in _STATEMENTS:
        for match in pattern.finditer(text):
            if in_comment(match.start()):
                continue
            lineno = text.count("\n", 0, match.start()) + 1
            if lineno in claimed:
                continue
            claimed.add(lineno)
            source = lines[lineno - 1].strip() if 0 < lineno <= len(lines) else ""
            hits.append((lineno, shape, source[:120]))
    return sorted(hits)


def main() -> int:
    try:
        files = go_files()
    except subprocess.CalledProcessError as exc:  # pragma: no cover - git is present or nothing runs
        print(f"check_no_stray_sql: SKIP: could not list tracked Go files: {exc}")
        return 2
    if not files:
        # An empty file set means the listing failed rather than that the repository has no Go, and
        # a gate that passes because it found nothing is the failure mode this file exists to
        # prevent. The same reasoning applies to the scan itself finding nothing to complain about.
        print("check_no_stray_sql: FAIL: no tracked Go files were listed, so nothing was checked")
        return 1

    violations: list[str] = []
    checked = 0
    for path in files:
        name = rel(path)
        if exempt_reason(name):
            continue
        checked += 1
        for lineno, shape, line in violations_in(path):
            violations.append(f"{name}:{lineno}: {shape}: {line}")

    if violations:
        print("check_no_stray_sql: FAIL: SQL reached the Go layer outside the generated package")
        for item in violations:
            print(f"  {item}")
        print(
            "\nGenerated accessors are the only sanctioned way for Go to reach PostgreSQL"
            " (sqlc.yaml). A query in a string does not have to agree with the schema, so a"
            " constraint the database enforces stops being enforced with no build error."
            " Put the statement in services/control-plane/db/queries and regenerate, or add an"
            " entry to EXEMPT with the reason it belongs there."
        )
        return 1

    # Checked and clean is not the same as checked, so the count is printed. A gate whose output
    # cannot be distinguished from a gate that did nothing is not evidence of anything.
    print(f"check_no_stray_sql: PASS ({checked} Go files outside the exemptions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())