"""One-off: append EV-068.

EV-067 closed the two gaps the earlier entries had left open. This one closes a larger gap in the
same artifact, found by asking a question nobody had asked: what is the G5 gate report actually
for, and what happens to it when the code moves on?

The answer was: nothing happens. The report was generated by hand, regenerated by hand, and
nothing failed when the tree changed underneath it. Every one of its digests was correct when
written and went stale silently, while the report continued to assert a PASS verdict and a
per-criterion mechanically_verified flag. A reviewer reading it had no way to tell it described
an older tree. That is the same defect the `sqlc is up to date` step catches for generated Go,
applied to the artifact a reviewer trusts to decide the gate passed - which makes it worse, not
better, because the failure is invisible and the document is authoritative by design.

Two changes. ARTEFACT_GLOBS now digests the generator that produces the verdict and the sqlc
config that produces the digested generated code, so the report's own premises and the provenance
of its machine-generated contents are both covered. And the generator gained a --check mode that
compares a full regeneration against the committed report byte-for-byte, wired into the go job
and into tests/ci.

The comparison is deliberately byte-for-byte rather than a digest recomputation, and that
distinction is the substance of the second case proven below: a report whose verdict was edited
by hand still has correct digests, so a digest-only check would pass it. A governance document
that can be edited to say PASS is exactly the thing that must not be checkable by digest alone.

Idempotent, append-only, written without a BOM.
"""

from __future__ import annotations

import io
import json
from pathlib import Path

BRAIN = Path(__file__).resolve().parents[1] / ".kilo" / "ecc" / "project-brain"
EVIDENCE_ID = "EV-068"
STAMP = "2026-10-01T15:40:00Z"

WORK_ITEM = "WI-141"

CLAIM = (
    "The G5 gate report was a snapshot with nothing tying it to the tree it describes. Its digests "
    "were correct when written and went stale silently, while the report kept asserting a PASS "
    "verdict and a per-criterion mechanically_verified flag, and nothing failed. It now digests the "
    "generator that produces its verdict and the sqlc config that produces its digested generated "
    "code, and a new --check mode fails when the committed report differs from a full "
    "regeneration. The check runs in the go job and in tests/ci."
)

METHOD = (
    "The question was asked rather than assumed: the report is the artifact a reviewer reads to "
    "decide G5 passed, so the failure that matters is the one where it says PASS about a tree it "
    "no longer describes. Searching for anything that asserted the report was current found "
    "nothing in verify_project_brain.py, in tests/ci, or in verify_toolchain.py, and the "
    "generator had no verify mode - it could only write. That is the defect, established rather "
    "than inferred. Two coverage gaps followed from reading what the report digests: "
    "scripts/generate_g5_gate_report.py was absent, so the program emitting the verdict and the "
    "mechanically_verified flag was unexamined by the report that carried them, and a version of "
    "it reporting PASS unconditionally would have produced a report still listing every artifact "
    "and still claiming the criteria were mechanically verified; and sqlc.yaml was absent while "
    "the sqlc output it configures was digested, so the rule that produced a digested result was "
    "unpinned while the result was pinned. The report cannot digest itself and does not try; "
    "hashing the generator closes the gap that is actually open. The check mode was made possible "
    "by a property verified before relying on it: the report is deterministic, because "
    "executed_at is a constant in the generator rather than a clock read, so regenerating an "
    "unchanged tree reproduces the same bytes. Had it embedded the current time, no byte-for-byte "
    "comparison would have been possible and the design would have had to be different. The mode "
    "was then proven in three cases, and the second is the one that justified byte-for-byte "
    "comparison over digest recomputation."
)

RESULT = (
    "ARTEFACT_GLOBS extended with sqlc.yaml and scripts/generate_g5_gate_report.py: the report now "
    "covers 80 artifact digests, up from 78, and both additions are present in the artifact list. "
    "The generator's own digest is correct rather than self-referential nonsense - recorded "
    "2262e602cd6e41f50ed82d574852b49f, matching sha256 of the file on disk - and regenerating an "
    "unchanged tree is idempotent, reporting 'unchanged' for both report files. The new --check "
    "mode exits 0 with 'G5 report is current (PASS, 80 artifact digests)' against a current "
    "report. It was proven to fail in two distinct cases and to pass in a third: a digested file's "
    "contents changed, exit 1; the report's verdict was hand-edited, exit 1; after both were "
    "restored byte-identically, exit 0. The second case is the one a digest-only check would have "
    "passed, since a hand-edited verdict leaves every recorded digest correct. Wired into the go "
    "job as 'the G5 gate report is current' after the drain mutation gate, and mirrored into "
    "tests/ci/test_g5_report_current.py, whose absence is a failure rather than a skip because a "
    "check that quietly stops running is precisely the failure mode this log keeps recording; the "
    "test was separately proven to fail against a stale report and to pass once the file was "
    "restored. Full re-verification after every change: gofmt clean; go vet exit 0 with and "
    "without the integration tag; default suite -race 10 packages ok; integration suite -race 17 "
    "passed, 0 failed, 0 skipped against a live PostgreSQL 17.11; toolchain gate 14 of 14; bash "
    "gate 40 of 40 run blocks; drain mutation gate PASS; G5 currency check PASS; tests/ci 117 "
    "passed, up from 116 by the new currency test; research worker 109 passed; backtest worker 47 "
    "passed; contracts VALID; project brain gate PASS; evidence-reference audit 0 items drifted; "
    "migration rehearsal PASSED; G5 report verdict PASS with 7 of 7 criteria PASS and "
    "mechanically verified. docs/ clean, nothing staged, nothing committed."
)

DEFECT_FOUND_AND_FIXED = (
    "One, and it is the largest of this work: the G5 gate report had no currency check. Not a "
    "false alarm this time - a gap found by asking what the artifact is for and then checking "
    "whether anything defended it, and nothing did. Three concrete consequences followed. A "
    "changed source file left the report asserting a verdict about older code. A changed generator "
    "was invisible, so the mechanism producing mechanically_verified could have been altered "
    "without the report revealing it. And a hand-edited verdict was undetectable by any digest "
    "scheme, because hand-editing the verdict does not disturb the digests it sits beside. The "
    "first is now covered by the byte-for-byte check, the second by digesting the generator, and "
    "the third specifically by the choice to compare full content rather than recompute digests. "
    "No false alarms were produced in this pass, which is itself worth noting against the five "
    "recorded in EV-067: the checks here were designed to be proven before being believed, and "
    "they were."
)

SIGNIFICANCE = (
    "The G5 report is the most trusted artifact in this work item and had the weakest guarantee. "
    "That inversion is the finding. Eighty digests of real code, a per-criterion "
    "mechanically_verified flag, a PASS verdict - and no mechanism tying any of it to the "
    "repository it described, so all of it decayed together and silently. The lesson generalises "
    "past this gate: an artifact's value to a reader depends entirely on whether it can be stale "
    "without anyone finding out, and a checksum list is not a currency check. A report that "
    "verifies its own inputs still says nothing about whether it was regenerated after they "
    "changed. The three additions here - digest the generator, digest the config, compare the "
    "whole document - are the minimum for a trust anchor to be worth trusting, and each closes a "
    "hole that the other two do not. The hand-edited-verdict case is the one worth remembering: it "
    "is invisible to every integrity scheme built on hashing content the document already contains, "
    "which is most of them, and it is precisely the case a governance document exists to prevent."
)

CAVEATS = (
    "Five limitations. First, the check compares against a report that must itself be committed, so "
    "until this work is committed the check is verifying a file the repository does not contain; on "
    "a clean checkout before that commit it will correctly report the report as missing. Second, "
    "the check fails whenever a legitimately digested file changes, which means an author who edits "
    "audit/chain.go must regenerate the report in the same change; that is the intended behaviour "
    "and matches how `sqlc is up to date` already behaves, but it is a new obligation on every "
    "future change to the digested set. Third, digesting the generator means any edit to it changes "
    "the report, so the two must be committed together for the same reason the six sqlc files must. "
    "Fourth, this closes staleness but not the underlying question of whether the G5 criteria are "
    "the right seven or whether PASS is the correct verdict; the check proves the report is "
    "current, not that its conclusions are sound. Fifth, and unchanged: human_reviewer remains null "
    "so WI-141 stays IN_PROGRESS; cross-store atomicity remains WI-120 and WI-121's and is not "
    "claimed; WI-117's unqualified audit and authz tables and RISK-14 remain other owners'; the "
    "schema-version forward problem is untouched; the write path is still not exposed over HTTP; the "
    "drain tests still drive the interrupt channel rather than a real signal; the mutation gate still "
    "writes a tracked file while running; and the `sqlc is up to date` CI step still fails until the "
    "six sqlc-related files are committed together. Everything here was verified on Windows, not on "
    "an Ubuntu runner. Nothing was staged and nothing was committed."
)

EXCEPTION = ""

ARTIFACTS = [
    "scripts/generate_g5_gate_report.py",
    "scripts/prove_g5_check_catches_stale.py",
    "tests/ci/test_g5_report_current.py",
    ".github/workflows/ci.yml",
    "evidence/gates/G5-gate-report.json",
    "evidence/gates/G5-gate-report.md",
    "sqlc.yaml",
    "scripts/record_ev068.py",
]

SUPERSEDES = []


def record() -> bool:
    store = BRAIN / "evidence.jsonl"

    line = json.dumps(
        {
            "schema": "ecc.project-brain/evidence/v7",
            "evidence_id": EVIDENCE_ID,
            "recorded_at": STAMP,
            "recorded_by": "team-lead",
            "work_item": WORK_ITEM,
            "claim": CLAIM,
            "status": "VERIFIED",
            "method": METHOD,
            "result": RESULT,
            "defect_found_and_fixed": DEFECT_FOUND_AND_FIXED,
            "significance": SIGNIFICANCE,
            "caveats": CAVEATS,
            "exception": EXCEPTION,
            "artifacts": ARTIFACTS,
            "supersedes": SUPERSEDES,
        },
        ensure_ascii=False,
    )

    if store.exists():
        for existing in store.read_text(encoding="utf-8").splitlines():
            if existing.strip() and json.loads(existing).get("evidence_id") == EVIDENCE_ID:
                print("unchanged: " + EVIDENCE_ID + " already recorded")
                return False

    with io.open(store, "a", encoding="utf-8", newline="\n") as handle:
        handle.write(line + "\n")
    print("recorded " + EVIDENCE_ID)
    return True


if __name__ == "__main__":
    record()
