package model

import (
	"errors"
	"testing"

	contracts "github.com/danarprastika/web-trade/contracts/go"
)

// modelBody and runBody are 26-character lowercase Crockford Base32 payloads, the fixed
// length identifier.schema.json requires.
const (
	modelBody = "01hq3k7m9x2f5rb8n0v6c4tqwx"
	runBody   = "01hq3k7m9x2f5rb8n0v6c4tqwy"
)

// Real sha-256 digests, generated by scripts/gen_model_digests.py. They are literals
// rather than computed values so that a change to the digest validation rules is visible as
// a test failure here rather than as a digest that happens to be well-formed for a new
// reason.
//
// The first version of these constants was 63 characters long. Digest.Valid rejected them,
// which was the validation working exactly as intended: a truncated digest is precisely what
// the check exists to catch, and loosening the length to make the fixtures pass would have
// removed the check this package's lineage guarantees rest on.
const (
	digestDataset  = Digest("f0ca4408f48085cf91bbdc24ba3f329017100a670800284574d560ff157c2f7a")
	digestEval     = Digest("70a6266c31acf586b9525343e40115389f402b6226632a81c85094c7abd4642b")
	digestRollback = Digest("d913f1a218f7f58d55ea6ec48024dfca770158c23cb7c28c7ea31d3829154b10")
	digestApproval = Digest("302b67afda9b5fd1c4c7d182cd5f17842706855e11bf0856d2355afa9d6d18ab")
	digestPrompt   = Digest("302dda7c20a2c090e2ffb33eb6ff99b637b8e627cea3a23c867fc8b6ec5041c0")
	digestContext  = Digest("03baf9a1d410a48ad4a345722266f86b4d20fdb31c53b3ad4135bd6a7725839a")
	digestResult   = Digest("fa047e4e547ec09c8131d4882b092e20672fb2894b43d8c38762ff2e21b32d36")
	digestArgs     = Digest("ac4c9b29e77f8f292b18392de2a6d059ca4151cda671c905d2ea21e320ecc854")
	digestArtifact = Digest("1b070c2c4233e5e43e8ee500f1b38c43ab4eccb0c6ea7da5da1f48ae4f7e8053")
)

func mustModelID(t *testing.T) contracts.Identifier {
	t.Helper()
	id, err := contracts.ParseIdentifier("mdl_" + modelBody)
	if err != nil {
		t.Fatalf("ParseIdentifier: %v", err)
	}
	return id
}

func mustRunID(t *testing.T) contracts.Identifier {
	t.Helper()
	id, err := contracts.ParseIdentifier("run_" + runBody)
	if err != nil {
		t.Fatalf("ParseIdentifier: %v", err)
	}
	return id
}

// validRecord builds a record with every required field populated, so a test can clear
// exactly one field and attribute the refusal to that field alone.
func validRecord() Record {
	return Record{
		ModelID:                    contracts.Identifier{},
		Version:                    "3.2.1",
		Owner:                      "owner-hquinn",
		Author:                     "pipeline-research-07",
		TrainingDatasetFingerprint: digestDataset,
		CodeRevision:               "9f3c1a7e5b2d8046af13c9e2b7d05f84a6c3e1d97b2a4f6c8e0d2b4a6f8c0e1d",
		FeatureSpecification:       "features/momentum_v4.yaml",
		EvaluationResults:          digestEval,
		Limitations:                "Degrades above 3x average volatility; untested on gaps > 5%.",
		DeploymentScope:            "BTCUSDT spot, shadow only",
		MonitoringPolicy:           "policy/drift_v2.yaml",
		RollbackArtifact:           digestRollback,
	}
}

func setID(t *testing.T, r Record) Record {
	t.Helper()
	r.ModelID = mustModelID(t)
	return r
}

// validRequest builds a request that satisfies the transition out of from, so a test can
// invalidate exactly one thing and attribute the refusal to that thing.
func validRequest(t *testing.T, from State, cmd Command, actor contracts.ActorType) Request {
	t.Helper()
	declared := byCmd[cmd]
	return Request{
		ModelID:                mustModelID(t),
		From:                   from,
		Command:                cmd,
		ActorID:                "reviewer-eklund",
		ActorType:              actor,
		PreconditionsSatisfied: []Precondition{declared.Precondition},
		IdempotencyKey:         "model-transition-0001",
		Reference:              string(digestApproval),
		Record:                 ptrRecord(validRecord()),
	}
}

func ptrRecord(r Record) *Record { return &r }

// Digest.String lets a caller render a digest where a string is required without losing the
// type distinction at the boundary.
func digestString(d Digest) string { return string(d) }

// TestDeclarationIsInternallyConsistent is the gate on the transition table itself. The
// table is the mechanism by which every other guarantee in this package is expressed, so a
// defect in it is a defect in all of them at once.
func TestDeclarationIsInternallyConsistent(t *testing.T) {
	if err := VerifyDeclaration(); err != nil {
		t.Fatalf("lifecycle declaration is inconsistent: %v", err)
	}
}

// TestEveryNonTerminalStateCanBeQuarantined is the property docs/25 section 6 depends on. If
// any state cannot reach QUARANTINED, a model sitting in that state could still be promoted
// after its workload was compromised.
func TestEveryNonTerminalStateCanBeQuarantined(t *testing.T) {
	for _, s := range AllStates() {
		if s.IsTerminal() {
			continue
		}
		found := false
		for _, next := range NextStates(s) {
			if next == StateQuarantined {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("state %s cannot reach QUARANTINED; a model in it survives a compromise", s)
		}
	}
}

// TestQuarantineIsNotResumableInPlace checks that clearing a quarantine routes through
// RETIRED rather than resuming the model in place. A quarantine a model can wave itself
// through is not a quarantine.
func TestQuarantineIsNotResumableInPlace(t *testing.T) {
	for _, to := range NextStates(StateQuarantined) {
		if to != StateRetired {
			t.Errorf("QUARANTINED leads to %s; a cleared model must retire and re-enter the "+
				"lifecycle rather than resume at %s", to, to)
		}
	}
}

// TestNoAgentActorIsPermittedAnywhere is docs/25 section 3.6 enforced structurally: an AI
// actor may never be the actor of record for a lifecycle change.
func TestNoAgentActorIsPermittedAnywhere(t *testing.T) {
	for _, tr := range transitions {
		for _, a := range tr.PermittedActors {
			if a == contracts.ActorAgent || a == contracts.ActorStrategy {
				t.Errorf("transition %s permits %s; an AI or strategy actor may not be the "+
					"actor of record for a lifecycle change", tr.Command, a)
			}
		}
	}
}

// TestNoModelMayAuthorizeItsOwnExecution is acceptance criterion two.
//
// The property is checked from both directions. A model cannot hold an actor id, so the
// self-authorization being prevented is the model supplying an approver it controls; the
// mechanical guarantee is that the approving transitions require a human actor AND a named
// approver who is neither the record's owner nor its author. A test that only checked the
// owner case would pass against an implementation that let the author approve.
func TestNoModelMayAuthorizeItsOwnExecution(t *testing.T) {
	// Every authority-bearing transition must be human-gated and must require an
	// independent approver.
	authorityBearing := []Command{CommandApprove, CommandPromote, CommandClearQuarantine}
	for _, cmd := range authorityBearing {
		tr, ok := byCmd[cmd]
		if !ok {
			t.Fatalf("command %s is not declared", cmd)
		}
		if !tr.RequiresIndependentApprover {
			t.Errorf("command %s carries authority but does not require an independent "+
				"approver; a check that can be satisfied by the author is not separation of "+
				"duties", cmd)
		}
		if !actorPermitted(tr, contracts.ActorHuman) {
			t.Errorf("command %s does not permit a human actor", cmd)
		}
		for _, forbidden := range []contracts.ActorType{
			contracts.ActorAgent, contracts.ActorService, contracts.ActorSystem, contracts.ActorStrategy,
		} {
			if actorPermitted(tr, forbidden) {
				t.Errorf("command %s permits %s; only a human may authorize a model", cmd, forbidden)
			}
		}
	}

	// The owner may not approve.
	rec := validRecord()
	req := validRequest(t, StateValidated, CommandApprove, contracts.ActorHuman)
	req.ActorID = rec.Owner
	req.Record = &rec
	if _, err := Apply(req); err == nil {
		t.Error("approval by the model owner was accepted; a record whose owner can approve " +
			"it has no independent reviewer")
	} else if !isSelfAuth(err) {
		t.Errorf("owner self-approval refused for the wrong reason: %v", err)
	}

	// The author may not approve. This is docs/07's literal requirement, and it is a
	// separate case from the owner because a pipeline is the normal author.
	req = validRequest(t, StateValidated, CommandApprove, contracts.ActorHuman)
	req.ActorID = rec.Author
	req.Record = &rec
	if _, err := Apply(req); err == nil {
		t.Error("approval by the model author was accepted; docs/07 forbids a research " +
			"author self-approving a model for live use")
	} else if !isSelfAuth(err) {
		t.Errorf("author self-approval refused for the wrong reason: %v", err)
	}

	// Omitting the record must not be a way to skip the independence check.
	req = validRequest(t, StateValidated, CommandApprove, contracts.ActorHuman)
	req.Record = nil
	if _, err := Apply(req); err == nil {
		t.Error("approval with no model record was accepted; supplying no record must not " +
			"skip the independence check")
	} else if !isSelfAuth(err) {
		t.Errorf("missing-record approval refused for the wrong reason: %v", err)
	}

	// An independent human is accepted, so the refusal above is the rule and not a blanket
	// denial of approvals.
	req = validRequest(t, StateValidated, CommandApprove, contracts.ActorHuman)
	if _, err := Apply(req); err != nil {
		t.Errorf("an independent human approval was refused: %v", err)
	}
}

// TestAgentCannotApproveOrPromote is the actor-type half of AC2, checked separately because
// it is the half a confused deputy would attempt: not self-approval, but delegation to a
// machine the model controls.
func TestAgentCannotApproveOrPromote(t *testing.T) {
	for _, cmd := range []Command{CommandApprove, CommandPromote} {
		for _, actor := range []contracts.ActorType{
			contracts.ActorAgent, contracts.ActorService, contracts.ActorSystem, contracts.ActorStrategy,
		} {
			req := validRequest(t, StateValidated, cmd, actor)
			if _, err := Apply(req); err == nil {
				t.Errorf("command %s was applied for actor %s; only a human may authorize "+
					"a model", cmd, actor)
			}
		}
	}
}

// TestApprovalRequiresAWellFormedApprovalArtifact ties the state change to the artifact
// that justifies it. An APPROVED model with no approval digest is precisely the gap
// docs/07 lists approval_record as a required field to close.
func TestApprovalRequiresAWellFormedApprovalArtifact(t *testing.T) {
	for _, ref := range []string{"", "approved", digestString(digestApproval)[:63]} {
		req := validRequest(t, StateValidated, CommandApprove, contracts.ActorHuman)
		req.Reference = ref
		out, err := Apply(req)
		if err != nil {
			continue
		}
		if ref == "" {
			t.Error("approval with no reference was accepted")
			continue
		}
		if !out.ApprovalRecord.Valid() {
			t.Errorf("approval accepted with malformed reference %q and produced an invalid "+
				"approval record", ref)
		}
	}
	req := validRequest(t, StateValidated, CommandApprove, contracts.ActorHuman)
	out, err := Apply(req)
	if err != nil {
		t.Fatalf("a well-formed approval was refused: %v", err)
	}
	if out.ApprovalRecord != digestApproval {
		t.Errorf("approval record = %q, want the referenced digest %q",
			out.ApprovalRecord, digestApproval)
	}
}

// TestUnknownStatesAndCommandsAreRejected checks the closed-set property. An unknown state
// or command must be refused rather than defaulted, because defaulting in a deployment
// lifecycle means deploying something nobody approved.
func TestUnknownStatesAndCommandsAreRejected(t *testing.T) {
	req := validRequest(t, StateValidated, CommandApprove, contracts.ActorHuman)
	req.From = "SHIPPED"
	if _, err := Apply(req); err == nil {
		t.Error("an unknown state was accepted; unknown states are unsupported, not defaults")
	}

	req = validRequest(t, StateValidated, CommandApprove, contracts.ActorHuman)
	req.Command = "model.shipped"
	if _, err := Apply(req); err == nil {
		t.Error("an unknown command was accepted")
	}
}

// TestCommandMustMatchTheClaimedState is the confused-deputy check: naming a real command
// that belongs to a different edge must fail rather than executing that other edge.
func TestCommandMustMatchTheClaimedState(t *testing.T) {
	req := validRequest(t, StateRegistered, CommandApprove, contracts.ActorHuman)
	if _, err := Apply(req); err == nil {
		t.Error("approval was applied from REGISTERED by naming the approve command while " +
			"claiming an unrelated state; the command must belong to the claimed edge")
	}
}

// TestIdempotencyKeyIsRequiredBecauseRetriesMustNotDoublePromote.
func TestIdempotencyKeyIsRequiredBecauseRetriesMustNotDoublePromote(t *testing.T) {
	for _, key := range []string{"", "short"} {
		req := validRequest(t, StateShadow, CommandPromote, contracts.ActorHuman)
		req.IdempotencyKey = key
		if _, err := Apply(req); err == nil {
			t.Errorf("promotion accepted with idempotency key %q", key)
		}
	}
}

// TestPreconditionMismatchIsRefused checks that a caller cannot satisfy a transition by
// asserting a different precondition name.
func TestPreconditionMismatchIsRefused(t *testing.T) {
	req := validRequest(t, StateRegistered, CommandRecordEvaluation, contracts.ActorService)
	req.PreconditionsSatisfied = []Precondition{PreconditionIndependentApproval}
	if _, err := Apply(req); err == nil {
		t.Error("evaluation was recorded by asserting an approval precondition")
	}

	// Asserting extra names alongside the required one is harmless.
	req = validRequest(t, StateRegistered, CommandRecordEvaluation, contracts.ActorService)
	req.PreconditionsSatisfied = append(req.PreconditionsSatisfied, PreconditionRollbackReady)
	if _, err := Apply(req); err != nil {
		t.Errorf("evaluation refused for asserting an extra precondition: %v", err)
	}
}

// TestUnattributedTransitionsAreRefused: an audit trail with no actor is not an audit
// trail.
func TestUnattributedTransitionsAreRefused(t *testing.T) {
	for _, mutate := range []func(*Request){
		func(r *Request) { r.ActorID = "" },
		func(r *Request) { r.ActorType = "" },
		func(r *Request) { r.ActorID = "   " },
	} {
		req := validRequest(t, StateRegistered, CommandRecordEvaluation, contracts.ActorService)
		mutate(&req)
		if _, err := Apply(req); err == nil {
			t.Error("a transition with no attributable actor was accepted")
		}
	}
}

// TestNonModelIdentifierIsRefused: a model id must carry the mdl_ prefix, so a decision or
// transition cannot be attributed to a strategy or an order.
func TestNonModelIdentifierIsRefused(t *testing.T) {
	other, err := contracts.ParseIdentifier("str_" + modelBody)
	if err != nil {
		t.Fatalf("ParseIdentifier: %v", err)
	}
	req := validRequest(t, StateRegistered, CommandRecordEvaluation, contracts.ActorService)
	req.ModelID = other
	if _, err := Apply(req); err == nil {
		t.Error("a transition on a non-model identifier was accepted")
	}
}

func isSelfAuth(err error) bool {
	return errors.Is(err, ErrSelfAuthorization)
}
